### ISSUE TITLE
12.1.0 errors with `Python is not set from command line or npm configuration`

### ISSUE THREAD

**Issue by k2xl** [firebase/firebase-admin-node#2552] opened 2024-05-10 01:22 UTC
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac Sonoma 14.0 (23A344)
  * Firebase SDK version: 12.1.0
  * Firebase Product: admin
  * Node.js version: 20.6.1
  * NPM version: 9.8.1

### [REQUIRED] Step 3: Describe the problem

Getting error when building on docker on Mac
`FROM node:20-alpine AS base`
https://github.com/sspenst/thinky.gg/pull/1101/files

Works fine on 12.0.0.

Error is below:
```
21.06 npm ERR! gyp info using node@20.13.1 | linux | arm64
21.06 npm ERR! gyp ERR! find Python 
21.06 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
21.06 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
21.06 npm ERR! gyp ERR! find Python checking if "python3" can be used
21.06 npm ERR! gyp ERR! find Python - executable path is ""
21.06 npm ERR! gyp ERR! find Python - "" could not be run
21.06 npm ERR! gyp ERR! find Python checking if "python" can be used
21.06 npm ERR! gyp ERR! find Python - executable path is ""
21.06 npm ERR! gyp ERR! find Python - "" could not be run
21.06 npm ERR! gyp ERR! find Python 
21.06 npm ERR! gyp ERR! find Python **********************************************************
21.06 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
21.06 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
21.06 npm ERR! gyp ERR! find Python you can try one of the following options:
21.06 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
21.06 npm ERR! gyp ERR! find Python (accepted by both node-gyp and npm)
21.06 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
21.06 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
21.06 npm ERR! gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
21.06 npm ERR! gyp ERR! find Python For more information consult the documentation at:
21.06 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
21.06 npm ERR! gyp ERR! find Python **********************************************************
21.06 npm ERR! gyp ERR! find Python 
21.06 npm ERR! gyp ERR! configure error 
21.06 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
21.06 npm ERR! gyp ERR! stack at PythonFinder.fail (/thinky_app/node_modules/node-gyp/lib/find-python.js:306:11)
21.06 npm ERR! gyp ERR! stack at PythonFinder.findPython (/thinky_app/node_modules/node-gyp/lib/find-python.js:164:17)
21.06 npm ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
21.06 npm ERR! gyp ERR! stack at async configure (/thinky_app/node_modules/node-gyp/lib/configure.js:27:18)
21.06 npm ERR! gyp ERR! stack at async run (/thinky_app/node_modules/node-gyp/bin/node-gyp.js:81:18)
21.06 npm ERR! gyp ERR! System Linux 5.15.49-linuxkit-pr
21.06 npm ERR! gyp ERR! command "/usr/local/bin/node" "/thinky_app/node_modules/.bin/node-gyp" "rebuild"
21.06 npm ERR! gyp ERR! cwd /thinky_app/node_modules/farmhash
21.06 npm ERR! gyp ERR! node -v v20.13.1
21.06 npm ERR! gyp ERR! node-gyp -v v10.1.0
21.06 npm ERR! gyp ERR! not ok
```

**Comment by ezequiel-imajine** [comment] 2024-05-10 15:32
Hi, I had a similar error with the same version of firebase admin and also on ARM. I changed my node version to 20.13 and updated my docker file by adding:
`RUN apk add --no-cache -u \
    curl \
    g++ \
    automake \
    autoconf \
    nasm \
    gcc \
    gifsicle \
    zlib \
    git \
    unzip\
    make\
    python3`

**Comment by lahirumaramba** [comment] 2024-05-14 18:46
This should also be related to https://github.com/firebase/firebase-admin-node/pull/2534
Which you can fix by upgrading `farmhash` to `v3.3.1`. We will also include this change in the upcoming release

**Comment by sspenst** [comment] 2024-05-22 04:09
I am seeing the same issue with farmhash 3.3.1

**Comment by mustafababil** [comment] 2024-05-22 14:08
Experiencing same here :/

**Comment by sspenst** [comment] 2024-05-22 20:53
@lahirumaramba FYI, should reopen this issue

**Comment by lahirumaramba** [comment] 2024-05-23 16:37
Hey folks, we will look into a better fix for this. In the meantime, are you able to add python to your docker image (or https://github.com/firebase/firebase-admin-node/issues/2552#issuecomment-2104813661) to and see if that resolves the issue?

**Comment by lahirumaramba** [comment] 2024-05-23 16:38
For others facing the same issue, it would help us if you can share more information on your environment and the errors you are seeing.

**Comment by lhermann** [comment] 2024-05-24 13:05
Here is the exact error:

```sh
/var/server # npm ci
npm error code 1
npm error path /var/server/node_modules/farmhash
npm error command failed
npm error command sh -c prebuild-install || node-gyp rebuild
npm error prebuild-install warn install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc=musl platform=linux)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@18.20.3 | linux | arm64
npm error gyp ERR! find Python
npm error gyp ERR! find Python Python is not set from command line or npm configuration
npm error gyp ERR! find Python Python is not set from environment variable PYTHON
npm error gyp ERR! find Python checking if "python3" can be used
npm error gyp ERR! find Python - executable path is ""
npm error gyp ERR! find Python - "" could not be run
npm error gyp ERR! find Python checking if "python" can be used
npm error gyp ERR! find Python - executable path is ""
npm error gyp ERR! find Python - "" could not be run
npm error gyp ERR! find Python
npm error gyp ERR! find Python **********************************************************
npm error gyp ERR! find Python You need to install the latest version of Python.
npm error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm error gyp ERR! find Python you can try one of the following options:
npm error gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm error gyp ERR! find Python (accepted by both node-gyp and npm)
npm error gyp ERR! find Python - Set the environment variable PYTHON
npm error gyp ERR! find Python - Set the npm configuration variable python:
npm error gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
npm error gyp ERR! find Python For more information consult the documentation at:
npm error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm error gyp ERR! find Python **********************************************************
npm error gyp ERR! find Python
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: Could not find any Python installation to use
npm error gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
npm error gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm error gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
npm error gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
npm error gyp ERR! System Linux 6.1.0-13-arm64
npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /var/server/node_modules/farmhash
npm error gyp ERR! node -v v18.20.3
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
```

Running inside a `node:18-alpine` docker container on the following environment:
`Linux 267451d27941 6.1.0-13-arm64 #1 SMP Debian 6.1.55-1 (2023-09-29) aarch64 Linux`

**Comment by lahirumaramba** [comment] 2024-05-24 15:23
Thanks @lhermann for the detailed response! Would adding `python` build tools to your docker helps? See: https://stackoverflow.com/a/59471030/1526201

How many of y'all facing this issue using the remote config API? I am wondering if we should make `farmhash` an optional dependency, so you would have to deal with this only if you are using the remote config API (which depends on `farmhash`).

**Comment by sspenst** [comment] 2024-05-25 00:06
Getting a similar error using the dockerfile here: https://github.com/sspenst/thinky.gg/blob/main/Dockerfile.dev

```
19.32 npm error code 1
19.32 npm error path /thinky_app/node_modules/farmhash
19.32 npm error command failed
19.32 npm error command sh -c prebuild-install || node-gyp rebuild
19.32 npm error prebuild-install warn install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc=musl platform=linux)
19.32 npm error gyp info it worked if it ends with ok
19.32 npm error gyp info using node-gyp@10.1.0
19.32 npm error gyp info using node@22.2.0 | linux | arm64
19.32 npm error gyp ERR! find Python 
19.32 npm error gyp ERR! find Python Python is not set from command line or npm configuration
19.32 npm error gyp ERR! find Python Python is not set from environment variable PYTHON
19.32 npm error gyp ERR! find Python checking if "python3" can be used
19.32 npm error gyp ERR! find Python - executable path is ""
19.32 npm error gyp ERR! find Python - "" could not be run
19.32 npm error gyp ERR! find Python checking if "python" can be used
19.32 npm error gyp ERR! find Python - executable path is ""
19.32 npm error gyp ERR! find Python - "" could not be run
19.32 npm error gyp ERR! find Python 
19.32 npm error gyp ERR! find Python **********************************************************
19.32 npm error gyp ERR! find Python You need to install the latest version of Python.
19.32 npm error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
19.32 npm error gyp ERR! find Python you can try one of the following options:
19.32 npm error gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
19.32 npm error gyp ERR! find Python (accepted by both node-gyp and npm)
19.32 npm error gyp ERR! find Python - Set the environment variable PYTHON
19.32 npm error gyp ERR! find Python - Set the npm configuration variable python:
19.32 npm error gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
19.32 npm error gyp ERR! find Python For more information consult the documentation at:
19.32 npm error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
19.32 npm error gyp ERR! find Python **********************************************************
19.32 npm error gyp ERR! find Python 
19.32 npm error gyp ERR! configure error 
19.32 npm error gyp ERR! stack Error: Could not find any Python installation to use
19.32 npm error gyp ERR! stack at PythonFinder.fail (/thinky_app/node_modules/node-gyp/lib/find-python.js:306:11)
19.32 npm error gyp ERR! stack at PythonFinder.findPython (/thinky_app/node_modules/node-gyp/lib/find-python.js:164:17)
19.32 npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19.32 npm error gyp ERR! stack at async configure (/thinky_app/node_modules/node-gyp/lib/configure.js:27:18)
19.32 npm error gyp ERR! stack at async run (/thinky_app/node_modules/node-gyp/bin/node-gyp.js:81:18)
19.32 npm error gyp ERR! System Linux 6.6.26-linuxkit
19.32 npm error gyp ERR! command "/usr/local/bin/node" "/thinky_app/node_modules/.bin/node-gyp" "rebuild"
19.32 npm error gyp ERR! cwd /thinky_app/node_modules/farmhash
19.32 npm error gyp ERR! node -v v22.2.0
19.32 npm error gyp ERR! node-gyp -v v10.1.0
19.32 npm error gyp ERR! not ok
```

Optional dependency could be a possible solution, we are currently only using the messaging API.

**Comment by KwamsC** [comment] 2024-06-01 17:40
Indeed same issue for me on 12.1.1

**Comment by Xhale1** [comment] 2024-06-05 01:27
@lahirumaramba my team isn't using the remote config api so that solution seems appealing (at least in our case).

This issue also occurs when using the `node:20-bookworm-slim` docker image as a base.

Thank you for looking into all of this, I appreciate it :)

**Comment by carusooo** [comment] 2024-06-10 22:14
This issue will sometimes resolve if the platform of the container is set to  `--platform=linux/amd64` although it can depend on your docker invocation (ex: works on a local mac build, fails on a github container build)

Setting the platform to amd64 allows for the prebuilt binary of `farmhash` to be fetched

**Comment by razvanilin** [comment] 2024-06-11 03:33
If making `farmhash` optional, I'd be all for that as my project does not use the remote config API. Alternatively, I can confirm that if I install python before installing the dependencies, it works as intended. It does increase my docker image quite a bit so for now I just downgraded firebase-admin to 12.0.0

Thanks for looking into this!

**Comment by lahirumaramba** [comment] 2024-06-11 15:07
Thanks for the additional context folks! We are also looking into switching to an alternative dependency https://www.npmjs.com/package/farmhash-modern that does not require `python`.
Let me run some tests with that as that seem to be a better option...

**Comment by chandrasekhar2039** [comment] 2024-06-18 18:00
If you are experiencing issues installing firebase-admin, you can try downgrading to `firebase-admin@12.0.0`.

Environment:

OS: Windows, macOS (Linux might work too)
Node version: 18+

Reason:
The issue is related to the `farmhash` dependency, which requires Python and node-gyp.

**Closed** 2024-06-19 17:36 UTC
Labels: api: core

**Comment by lahirumaramba** [comment] 2024-06-20 19:58
Hey folks, we replaced `farmhash` with `farmhash-modern` in `v12.2.0`. Please test with the latest `firebase-admin` `v12.2.0` and let us know if you run into any issues. Thanks!

**Comment by SnowMarble** [comment] 2024-06-21 01:21
works well on docker build with bun:1.1.13-alpine

**Comment by hassanzadeh** [comment] 2024-09-16 03:55
Hi @lahirumaramba ,
Can you elaborate what you did exactly? the farmhash is used under the hood right by firebase-admin, how did you replace it?
THanks
