### ISSUE TITLE
Firebase Admin (Nodejs) crashes because of error "A bucket name is needed to use Cloud Storage"

### ISSUE THREAD

**Issue by tphduy** [firebase/firebase-admin-node#281] opened 2018-05-29 13:36 UTC
I am using a Firebase admin in Node.js and I am not going to use Cloud Storage in my own server, firebase app initialization working well before but it crash today because of error "A bucket name is needed to use Cloud Storage".
So I tried to integrate cloud storage to fix it but it did not work.
const admin = require('firebase-admin')
const serviceAccount = require('./letseat-dd347-firebase-adminsdk-op4zs-3ad050a59d.json')
admin.initializeApp({
credential: admin.credential.cert(serviceAccount),
storageBucket: 'letseat-dd347.appspot.com'
})

Environment details

OS: MacOS High Sierra
Node.js version: 10.2.1
npm version: 5.6.0
Firebase version: 5.12.1
@google-cloud/storage version: lasted
Steps to reproduce

npm install
nodemon or node app.js or nom start.
=> Crashing because of error: A bucket name is needed to use Cloud Storage.
<img width="689" alt="screen shot 2018-05-29 at 6 43 42 pm" src="https://user-images.githubusercontent.com/16264018/40659919-d5bad44c-6379-11e8-8355-971cc09643d6.png">

**Comment by hiranya911** [comment] 2018-05-29 17:13
What's at `routes/restaurant.js` line 10?

**Comment by tphduy** [comment] 2018-05-30 08:29
Thí 
<img width="967" alt="screen shot 2018-05-30 at 3 27 52 pm" src="https://user-images.githubusercontent.com/16264018/40708627-25a31a74-641e-11e8-8042-0f222a6d8e94.png">
this is my restaurant.js.
I don't know why I did not use Cloud Storage on my own server but It still keep crashing?

**Comment by hiranya911** [comment] 2018-05-30 17:02
This is not useful. I expected to see references to `admin` in your code, but there aren't any in the above file. And interestingly, your stacktrace doesn't have any Admin SDK references either. I think something else in your code is trying to load the Cloud Storage module. Admin SDK doesn't load it unless `admin.storage()` is invoked explicitly. Can you share the file where Admin SDK is actually used/initialized?

**Comment by hiranya911** [comment] 2018-06-27 23:12
Closing this due to lack of information. Please reopen with a minimal, reproducible test case if you want us to follow up.

**Closed by hiranya911** 2018-06-27 23:12 UTC
