### ISSUE TITLE
[FR] Export Errors For Use

### ISSUE THREAD

**Issue by enchorb** [firebase/firebase-admin-node#1741] opened 2022-06-04 15:44 UTC
**Is your feature request related to a problem? Please describe.**
Need to detect if an error is an `instanceof FirebaseError`

**Describe the solution you'd like**
Add error utils to module exports so can be used without the error below

**Additional context**
Currently when `import { FirebaseError } from 'firebase-admin/lib/utils/error'`  get the following error `Error: Package subpath './lib/utils/error' is not defined by "exports" in /Users/.../node_modules/firebase-admin/package.json`

**Comment by lahirumaramba** [comment] 2022-06-09 19:47
The correct import should be `import { FirebaseError } from 'firebase-admin';`. Could you please check if that works for you? I think this is a duplicate of #1666. Let's close this and continue the discussion in #1666

**Closed by lahirumaramba** 2022-06-09 19:47 UTC
Labels: needs-triage, type: feature request
