### ISSUE TITLE
onSnapshot exceeds retries?

### ISSUE THREAD

**Issue by DamnMerc** [firebase/firebase-admin-node#585] opened 2019-06-25 21:08 UTC
* Operating System version: _1809____
  * Firebase SDK version: __8.2.0___
  * Library version: ___8.2.0__
  * Firebase Product: __database___ (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem
After I'd say 2-3 hours, it'll error that I exceeded maximum retries. I've searched for any relevant encounters with this to try to fix but couldn't find any.
![image](https://user-images.githubusercontent.com/8603387/60133628-b1b16a80-976b-11e9-9e4b-eb6fae11f557.png)
![image](https://user-images.githubusercontent.com/8603387/60133648-ba09a580-976b-11e9-813b-597698fbf7a6.png)

#### Steps to reproduce:

I'd honestly say just wait 2-3 hours and it should occur on it's own.

**Comment by schmidt-sebastian** [comment] 2019-07-01 17:29
@DamnMerc Thanks for reporting this. Can you send us logs from your client? You can enable logging by invoking 

```
admin.firestore.setLogFunction(console.log);
```

Thanks!

**Comment by matej-svejda** [comment] 2019-07-07 11:39
Im not the original reporter, but Im experiencing the same issue and I managed to reproduce it with logging enabled (basically I just have to wait a few hours). Here are the logs:
[firestore_max_retries.txt](https://github.com/firebase/firebase-admin-node/files/3365562/firestore_max_retries.txt)

**Comment by DamnMerc** [comment] 2019-07-07 17:30
> 
> 
> Im not the original reporter, but Im experiencing the same issue and I managed to reproduce it with logging enabled (basically I just have to wait a few hours). Here are the logs:
> [firestore_max_retries.txt](https://github.com/firebase/firebase-admin-node/files/3365562/firestore_max_retries.txt)

Thanks for this! Everytime this happened I wasn't at home, so I couldn't catch the errors without it already passing in console.

**Comment by schmidt-sebastian** [comment] 2019-07-08 18:18
I'm not 100% sure I found the root cause for your issue, but the logs do show that we are performing extra retries for each error. The retries can then again cause more retries, which could explain why you are quickly exceeding the retry limit of ten. Once https://github.com/googleapis/nodejs-firestore/pull/713 we can try and see if the behavior improves.

**Comment by schmidt-sebastian** [comment] 2019-07-08 22:23
@DamnMerc / @matej-svejda Can you update to v2.2.4 to see if this improves the behavior?

**Comment by matej-svejda** [comment] 2019-07-09 00:03
@schmidt-sebastian I upgraded, lets see what happens :)

Do you have any ideas what is causing the connection to get lost in the first place? Im running this on an AWS server, so my guess is connectivity shouldnt be an issue ;)

**Comment by schmidt-sebastian** [comment] 2019-07-09 16:35
My theory is that you are either seeing a random connection drops, which can happen even over a strong network link, or you are running into our authentication deadline, in which case our backend terminates your connection (it should however not return GRPC Error Code 13) and we should retry seamlessly.

From your logs, however, it seems like we did not handle these connectivity issues correctly. For every connection drop, it looks like we tried to re-establish the connection twice. This then quickly ballooned, as the second connection drop started 4 retry attempts. Then we have 8 and finally 16. Since our limit is 10, you saw the "Exceeded maximum retries" error when we hit the fourth network drop.

**Comment by matej-svejda** [comment] 2019-07-10 09:00
If I understand you correctly, this means that for this error to have happend, connecting should have failed multiple times in short succession (too short in this case). Can this then even be random connection drops or authentification deadlines?

Can I provide you with any more info to find out why the Errror Code 13 happened in the first place?

**Comment by schmidt-sebastian** [comment] 2019-07-10 15:54
Unfortunately, there is no metadata for the internal error you are seeing. If these errors occur repeatedly, you can file a [Google Support Ticket](https://firebase.google.com/support/troubleshooter/contact/) with your Project ID and get more information from the backend team.

**Comment by matej-svejda** [comment] 2019-07-13 12:28
So far the reconnects on v2.2.4 seem to always be successful, so that part appears to be fixed.

**Comment by schmidt-sebastian** [comment] 2019-07-14 00:26
Glad to hear! I'm closing this for now.

**Closed by schmidt-sebastian** 2019-07-14 00:26 UTC
Labels: api: firestore

**Comment by bikevit2008** [comment] 2022-11-18 14:23
Hm, i got this problem with using "firebase-admin": "^11.2.0" and with this code
`
const { cert } = require('firebase-admin/app');
const admin = require('firebase-admin')
admin.initializeApp({
  credential: cert(serviceAccount),
  // databaseURL: DATABASE_URL
})
const db = admin.firestore()`

Hello:)
