### ISSUE TITLE
[BUG] Firebase auth triggers timeout

### ISSUE THREAD

**Issue by bolds07** [firebase/firebase-admin-node#1233] opened 2021-04-21 16:52 UTC
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: GCF
  * Firebase SDK version:  9.4.2 [already tried 9.6.0 and it has exact same proble]
  * Firebase Product: auth (auth, database, storage, etc)
  * Node.js version: 10
  * NPM version: I've no idea what version google uses

### [REQUIRED] Step 3: Describe the problem
I’ve been working on an Android project for over 3 years now. Since beginning my project uses Firebase for many purposes including authentication.
Nowadays has grown a lot and I got a few thousand users per day and many hundreds users per hour. With this expansion I started noticing some errors that weren’t before [or weren’t that noticiable]
I use a firebase function to authenticate my users. The function is simple it validates a request cryptographic signature (to guarantee that it came from my app and not from someone bruteforcing it), then extract the parameters and query the firebase database for that credentials (only 1 result/or no result, will always been returned) if everything is okay a firebase authentication token is created and returned to user.
I’m using GCF with node 10 runtime, 40 seconds timeout and 128MB memory limit

```
const admin = require('firebase-admin');
admin.initializeApp({
});

const auth = admin.auth();
const igDatabase = admin.database();
const ServerValue = admin.database.ServerValue;

const crypto = require("crypto");
 exports.auth = (req, res) => {
    if (validateReqParams(req.body)) {

        if (validateCredentials(req.body)) {
	//here I extract the params from the json body
            authenticate(uid, newUser, regDate, res);
        } else
            invalidRequest('invalid body.d', req.body.d, res);

    } else
        invalidRequest('body.s doesn\'t match', req.body, res);

};


function validateReqParams(body) {

    return body && body.sign && body.data && body.sign == crypto.createHmac('sha256', 'my key').update(body.data).digest('hex');

}

function invalidRequest(error, item, res) {
    console.error(error);
    console.log(JSON.stringify(item));
    res.end();
}

function authenticate(uid, newUser, regDate, res) {
    auth.createCustomToken(uid).then(function(customToken) {

        res.status(200).json({
            t: customToken,
            n: newUser,
            r: regDate
        });
    }).catch(function(error) {
        console.error("Error creating custom token: " + JSON.stringify(error));
        res.status(200).json({
            e: error
        });
    });

}

```

 I wont copy the validate credentials function because is a long code, but there ARENT any loops or recursion, neither it allocates memory, it just query few data from database each query having possible result 1 boolean or no data…

This is a VERY SIMPLE set up, I have few hundreds requests per hour with an average of 250 ms processing time and 99% of requests being faster than 300ms. But once and while one request takes 40,000 ms seconds and then is finished due timeout

I’ve extensively tried to debug and find the problem without the success, I even collected the exact params from the requests that caused timeout and tried to bruteforce the function with these params to see if at any point it would timeout, it DIDN’T

From the debug data I could collect, I noticed the timeout happens at the    ` auth.createCustomToken(uid) `call (I’ve place many debug code and monitored few hundreds executions and the only debug lines those where missing where after this function call)

Sent many emails to firebase support [which were ignored] and I couldn’t find the exact root cause of the problem… but with a look over the firebase function metrics charts and all the data I collected I’ve few hypotesys

![image](https://user-images.githubusercontent.com/19866062/115591474-82f17600-a2a8-11eb-828e-9fa97372113f.png)

Both these charts correspond of the same 24 hours period. I placed some dash lines to show how synchronized the peak execution times are compared to the garbage collection time… This tendency is even more noticiable on charts from shorter periods

![image](https://user-images.githubusercontent.com/19866062/115591516-8be24780-a2a8-11eb-8285-332d9d84108b.png)

These charts now show a six hours interval… and It is clear that the execution times peak COMES IN A VERY REGULAR 30 MINUTES INTERVAL… the thing is so regular that this image almost looks like a heart peacemaker chart. 
Also noticiabe, these peaks are aligned with a memory peak followed by a discharge

With all that being said these are my conclusions.
1-	The memory grows very slowly and if you ignore the peak the second highest level is only 10% higher than the average level… so there is low chance of this being a memory leak from my code
2-	The memory peak/discharge are very fast, similar what we would expect from a garbage collection routine.

With all the exposed data I come to ask:
1-	Is it possible that garbage collection is affecting the node execution?
2-	Is the natural garbage collection execution memory supposed to account for the whole memory allocated by the cloud function?
3-	Is possible that the firebaseauth has a memory leak that causes all this?
4-	Does anyone faces the same issue? Is there anything I can do to solve?

**Comment by hiranya911** [comment] 2021-04-21 17:53
You can try v9.5.0 to see if this is same as #1231.

**Comment by hiranya911** [comment] 2021-04-22 20:32
You can verify which version of the library you're using by just adding a log statement to your code:

```
console.log('Firebase Admin version:', admin.SDK_VERSION);
```

**Comment by bolds07** [comment] 2021-04-22 22:59
![image](https://user-images.githubusercontent.com/19866062/115794846-21630180-a3a5-11eb-9cf7-cdecf3631383.png)

is there a debug flag that i can set anywhere to debug auth inner calls?

**Comment by hiranya911** [comment] 2021-04-23 18:06
Depending on how you're initializing the SDK, `createCustomToken()` may be an entirely local operation, or may result in an API call to Cloud IAM. If it's the latter, you can try to log the API call to see if there's some problem there ([this article](https://medium.com/coding-gym/logging-http-calls-made-by-node-js-and-python-applications-5607df1b7139) provides some instructions on how to setup a global HTTP request logger for Node.js).

I also just merged #1234 to the main branch. If you're interested, you can try this fix with one of your functions and see if it resolves the issue. I'm happy to share the steps for this if you want to try it out urgently. If not wait for the next release to come out in a few more days.

**Comment by bolds07** [comment] 2021-04-23 18:16
I'm initializing the sdk like this:

```
const admin = require('firebase-admin');
admin.initializeApp({
    serviceAccountId: 'authenticator@igibo-b0b27.iam.gserviceaccount.com',
    databaseURL: "https://igibo-b0b27.firebaseio.com",
    projectId: "igibo-b0b27"
});

const auth = admin.auth();
const igDatabase = admin.database();
const ServerValue = admin.database.ServerValue;
```

Should I do another way?

As this issue has just a minor effect I'm willing to wait for the release [if it takes a week or so]. 
Anyway I would like to thank you for the patience and effort you put to solve the matter... also for your patience dealing with us

**Comment by hiranya911** [comment] 2021-04-23 18:54
You're welcome :) And I'm sorry we haven't been able to find a specific cause for this issue yet. 

Your initialization code looks ok. It should cause an API call to be made to Cloud IAM. You can try to log it as indicated in my earlier comment, and see if it reveals any new information.

FWIW, I don't think this is exactly a leak. Leaks show up as gradual growth of resource usage over time, while your charts show sharp spikes at fairly regular intervals. Something is triggering that anomalous behavior every 25 minutes or so similar to #1231. But the fact that you can see this behavior with old versions of the SDK like v9.4.2, makes it difficult to draw any conclusions. 

Let's hope the fix in #1234 helps with this problem too. At least, it should rule out the one known livelock issue with RTDB on GCF.

**Comment by misha-reyzlin-hier** [comment] 2021-05-03 17:07
@hiranya911 thanks for the analysis and your work on the issue.

Do you have a timeline what release is expected to have the fixes for this? 

We had to downgraded from 9.6.0 to 9.2.0 because we have experienced these timeouts on our staging environment during testing.

**Comment by hiranya911** [comment] 2021-05-03 17:34
It's already released. 9.7.0 available for download now.

**Comment by hiranya911** [comment] 2021-05-07 19:24
@bolds07 have you had a chance to test with the latest release?

**Comment by bolds07** [comment] 2021-05-08 00:28
It solved my problem!

BTW do you have any contact in the android sdk? i've opened 2 issues that i'm facing and they got 'forgotten' by the engineers there 

https://github.com/firebase/firebase-android-sdk/issues/2604

this issue is very old and consitly happens even in the latests versions of the android sdk
https://github.com/firebase/firebase-android-sdk/issues/1985

**Comment by hiranya911** [comment] 2021-05-08 03:49
Thanks @bolds07 for confirming. I'll close this issue as resolved shortly.

@vkryachko @schmidt-sebastian can you take a look at the Android SDK issues when you get a chance?

**Closed by hiranya911** 2021-05-08 03:49 UTC
Labels: api: auth

**Comment by bolds07** [comment] 2021-05-09 22:08
@hiranya911, Some bad news I'm still getting some timeouts...

just a quick review, I updated firebase-admin to 9.7.0 on may 4th and then it was fine... 
but from may 7th and on I started having some timeouts... Not as many as before, but since May 7th I get 4 timeouts per day (nothing something that worries me)

I didn't update or change anything else in this function and this function is hit MORE than 20 thousand times per day (btw would be good if GC dashboard shows how many times the function is called per period of time)

so it seems weird to me that the function got 3 days fine after updating [even being called 100k times] and since then gets a few timeouts


https://ibb.co/d478LKR

also the metrics graphics are very different from those i post at begining, not having those memory spikes

https://ibb.co/Qvr5NLh

**Comment by ganey** [comment] 2021-07-05 10:57
Do the timeouts on GCF happen on cold starts? Or just randomly? 

There is still an issue with firestore loaded though the admin SDK that causes it to sometimes take say 9 seconds to load, call firestore and do some auth.

There's a thread on Google groups about it, but it doesn't seem like Google are interested in fixing the random slowness on cold starts. The issue is over a year old and they have plenty of replication examples.
