### ISSUE TITLE
[FR] Workload Identify Federation 

### ISSUE THREAD

**Issue by enchorb** [firebase/firebase-admin-node#2168] opened 2023-04-30 17:25 UTC
This library does not work with the credential generated by WLIF (type "external_account").

WLIF is recommended best practice across all Google docs, and other Google libraries / Firebase libraries in different languages have support for this.

**Comment by lahirumaramba** [comment] 2023-05-01 21:00
Duplicate of #1377 
We are currently working on migrating credentials to `google-auth-library-nodejs`, which will fix this issue. Please follow #1377 for updates.

**Closed by lahirumaramba** 2023-05-01 21:00 UTC
Labels: needs-triage, type: feature request
