### ISSUE TITLE
[Firestore] hangs indefinitely

### ISSUE THREAD

**Issue by ryanccn** [firebase/firebase-admin-node#1162] opened 2021-02-09 12:03 UTC
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Big Sur v11.2
  * Firebase SDK version: 8.13.0
  * Firebase Product: Firestore
  * Node.js version: v15.8.0
  * NPM version: 7.5.0

#### Steps to reproduce:

Doing anything with Firestore hangs indefinitely. After testing with `resolution`s of `@grpc/grpc-js`,

- <0.6.0: returns "Protocol https: unsupported"
- 0.6.0: API returns` {"error":{}}`
- \>0.6.0: hangs indefinitely (returns an error message like this:)

```
node:events:355
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.cancelWithStatus (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:442:14)
    at ChannelImplementation.tryPick (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:232:32)
    at ChannelImplementation._startCallStream (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:262:14)
    at Http2CallStream.start (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:419:22)
    at BaseStreamingInterceptingCall.start (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:276:19)
    at ServiceClientImpl.makeServerStreamRequest (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:311:14)
    at ServiceClientImpl.<anonymous> (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/make-client.js:92:19)
    at /Users/ryanccn/firebase/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:201:29
    at /Users/ryanccn/firebase/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
    at /Users/ryanccn/firebase/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
Emitted 'error' event on ClientReadableStreamImpl instance at:
    at Object.onReceiveStatus (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:328:28)
    at Object.onReceiveStatus (/Users/ryanccn/firebase/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    [... lines matching original stack trace ...]
    at /Users/ryanccn/firebase/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at Object.request (/Users/ryanccn/firebase/node_modules/google-gax/build/src/streamingCalls/streaming.js:105:36) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

#### Relevant Code:

http://github.com/leerob/nextjs-vercel-firebase

```js
// lib/firebase.js

import admin from 'firebase-admin';

try {
  admin.initializeApp({
    credential: admin.credential.cert({
      project_id: process.env.FIREBASE_PROJECT_ID,
      private_key: process.env.FIREBASE_PRIVATE_KEY,
      client_email: process.env.FIREBASE_CLIENT_EMAIL
    }),
    databaseURL: 'https://ryanccn-dev-36130-default-rtdb.firebaseio.com/'
  });
} catch (error) {
  /*
   * We skip the "already exists" message which is
   * not an actual error when we're hot-reloading.
   */
  if (!/already exists/u.test(error.message)) {
    // eslint-disable-next-line no-console
    console.error('Firebase admin initialization error', error.stack);
  }
}

export default admin.firestore();
```

(This is a Next.js API route)

```js
// pages/api/city/[name].js

import firebase from '../../../lib/firebase';

export default (req, res) => {
  console.log()
  firebase
    .collection('cities')
    .doc(req.query.name)
    .get()
    .then((doc) => {
      res.json(doc.data());
    })
    .catch((error) => {
      res.json({ error });
    });
};
```

**Comment by ryanccn** [comment] 2021-02-09 12:04
@google-oss-bot I deleted the first step thinking it was unnecessary

**Comment by schmidt-sebastian** [comment] 2021-02-10 20:48
Firestore uses `@grpc/grpc-js`. Are you able to share your output of `npm list`?

**Comment by ryanccn** [comment] 2021-02-11 14:16
> Firestore uses `@grpc/grpc-js`. Are you able to share your output of `npm list`?

Yeah I meant `grpc-js` 😅

**Comment by ryanccn** [comment] 2021-02-11 14:17
```
nextjs-vercel-firebase@0.0.0
├── firebase-admin@8.12.1
├── next@9.4.0
├── react-dom@16.13.1
├── react@16.13.1
└── swr@0.2.0
```

**Comment by cprichmond** [comment] 2021-02-12 00:17
I'm having a similar issue. 

When I follow the instructions found here: https://firebase.google.com/docs/admin/setup I get the same `Error: 14 UNAVAILABLE: No connection established` after about a 60-second wait.

I'm using...

``` 
node 12.19.0 (have also tried 15.x)
firebase-admin: ^9.4.2
```

Am just performing a simple get on a document that exists in a collection that exists (very similar to the code above). I have used firestore successfully in the past with node without issue. Happy to provide more context for my specific case if needed.

**Comment by ryanccn** [comment] 2021-02-13 11:15
@schmidt-sebastian interestingly this problem doesn't exist on a DigitalOcean droplet I created for the purpose 🧐

<img width="682" alt="Screen Shot 2021-02-13 at 19 14 41" src="https://user-images.githubusercontent.com/70191398/107848618-c5717f00-6e2f-11eb-9a53-94cddae4f43e.png">

**Comment by cprichmond** [comment] 2021-02-14 06:23
@ryanccn perhaps this is mac related? I am on `macOS Catalina 10.15.7`

I dropped the Firebase Admin SDK back to 7.x and got the following error: 

`Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.`

Could be a red herring, but thought it was worth mentioning.

**Comment by ryanccn** [comment] 2021-02-14 09:09
Hmm.

**Comment by ryanccn** [comment] 2021-02-14 09:10
Hmm.

**Comment by schmidt-sebastian** [comment] 2021-02-17 20:56
Note that you can turn on additional logging by setting the following environment variables:

```
GRPC_VERBOSITY= DEBUG GRPC_TRACE=all
```

This should show extensive logging output and might point us to the root cause.

**Comment by cprichmond** [comment] 2021-02-18 02:49
Thanks for the tip @schmidt-sebastian. Here are the subsequent logs and errors which look very similar to those I received when I dropped back to 7.x of the SDK...

I can paste the full logs but here are the relevant repeating parts. Seems to be an issue with the certificate.

```
2021-02-18T02:42:45.479Z | pick_first | CONNECTING -> CONNECTING
2021-02-18T02:42:45.479Z | resolving_load_balancer | dns:firestore.googleapis.com:443 CONNECTING -> CONNECTING
2021-02-18T02:42:45.479Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2021-02-18T02:42:45.480Z | connectivity_state | dns:firestore.googleapis.com:443 CONNECTING -> CONNECTING
2021-02-18T02:42:45.649Z | subchannel | 2404:6800:4015:802::200a:443 connection closed with error self signed certificate in certificate chain
2021-02-18T02:42:45.649Z | subchannel | 2404:6800:4015:802::200a:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-18T02:42:45.649Z | pick_first | CONNECTING -> CONNECTING
2021-02-18T02:42:45.649Z | resolving_load_balancer | dns:firestore.googleapis.com:443 CONNECTING -> CONNECTING
2021-02-18T02:42:45.649Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2021-02-18T02:42:45.649Z | connectivity_state | dns:firestore.googleapis.com:443 CONNECTING -> CONNECTING
2021-02-18T02:42:45.650Z | subchannel | 142.250.70.234:443 connection closed with error self signed certificate in certificate chain
2021-02-18T02:42:45.650Z | subchannel | 142.250.70.234:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-18T02:42:45.650Z | pick_first | CONNECTING -> TRANSIENT_FAILURE
2021-02-18T02:42:45.650Z | resolving_load_balancer | dns:firestore.googleapis.com:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-18T02:42:45.650Z | channel | Pick result: TRANSIENT_FAILURE subchannel: undefined status: 14 No connection established
2021-02-18T02:42:45.650Z | call_stream | [0] cancelWithStatus code: 14 details: "No connection established"
2021-02-18T02:42:45.650Z | call_stream | [0] ended with status: code=14 details="No connection established"
2021-02-18T02:42:45.651Z | connectivity_state | dns:firestore.googleapis.com:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-18T02:42:45.651Z | call_stream | [0] cancelWithStatus code: 1 details: "Cancelled on client"
2021-02-18T02:42:46.484Z | subchannel | 2404:6800:4015:802::200a:443 TRANSIENT_FAILURE -> CONNECTING
2021-02-18T02:42:46.484Z | pick_first | TRANSIENT_FAILURE -> CONNECTING
```

**Comment by cprichmond** [comment] 2021-02-18 03:06
Upon further reading of the above issue. I think I am the victim of corporate malware. This is a work MacBook and subsequently has Netskope and god knows what else monitoring and messing with SSL traffic. I added `export NODE_TLS_REJECT_UNAUTHORIZED=0` and this got me further down the road. I am going to run this on a non-work regulated Mac; if that works then it's pretty obvious where the issue lies. Not sure if there is a fix for it though as I can't disable the corporate malware.

**Comment by ryanccn** [comment] 2021-02-19 09:18
```
2021-02-19T09:13:14.252Z | resolving_load_balancer | dns:firestore.googleapis.com:443 IDLE -> IDLE
2021-02-19T09:13:14.252Z | connectivity_state | dns:firestore.googleapis.com:443 IDLE -> IDLE
2021-02-19T09:13:14.253Z | dns_resolver | Resolver constructed for target dns:firestore.googleapis.com:443
2021-02-19T09:13:14.262Z | channel | dns:firestore.googleapis.com:443 createCall [0] method="/google.firestore.v1.Firestore/BatchGetDocuments", deadline=Fri Feb 19 2021 17:18:14 GMT+0800 (China Standard Time)
2021-02-19T09:13:14.264Z | call_stream | [0] Sending metadata
2021-02-19T09:13:14.264Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2021-02-19T09:13:14.266Z | call_stream | [0] write() called with message of length 213
2021-02-19T09:13:14.266Z | call_stream | [0] end() called
2021-02-19T09:13:14.267Z | call_stream | [0] deferring writing data chunk of length 218
2021-02-19T09:13:14.268Z | dns_resolver | Resolution update requested for target dns:firestore.googleapis.com:443
2021-02-19T09:13:14.271Z | resolving_load_balancer | dns:firestore.googleapis.com:443 IDLE -> CONNECTING
2021-02-19T09:13:14.271Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2021-02-19T09:13:14.271Z | connectivity_state | dns:firestore.googleapis.com:443 IDLE -> CONNECTING
2021-02-19T09:13:14.271Z | resolving_load_balancer | dns:firestore.googleapis.com:443 CONNECTING -> CONNECTING
2021-02-19T09:13:14.271Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2021-02-19T09:13:14.271Z | connectivity_state | dns:firestore.googleapis.com:443 CONNECTING -> CONNECTING
2021-02-19T09:13:14.452Z | dns_resolver | Resolved addresses for target dns:firestore.googleapis.com:443: [172.217.4.138:443]
2021-02-19T09:13:14.452Z | pick_first | IDLE -> IDLE
2021-02-19T09:13:14.453Z | resolving_load_balancer | dns:firestore.googleapis.com:443 CONNECTING -> IDLE
2021-02-19T09:13:14.453Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2021-02-19T09:13:14.453Z | connectivity_state | dns:firestore.googleapis.com:443 CONNECTING -> IDLE
2021-02-19T09:13:14.453Z | pick_first | Connect to address list 172.217.4.138:443
2021-02-19T09:13:14.454Z | subchannel | 172.217.4.138:443 refcount 0 -> 1
2021-02-19T09:13:14.454Z | subchannel | 172.217.4.138:443 refcount 1 -> 2
2021-02-19T09:13:14.454Z | pick_first | Start connecting to subchannel with address 172.217.4.138:443
2021-02-19T09:13:14.454Z | pick_first | IDLE -> CONNECTING
2021-02-19T09:13:14.455Z | resolving_load_balancer | dns:firestore.googleapis.com:443 IDLE -> CONNECTING
2021-02-19T09:13:14.455Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2021-02-19T09:13:14.455Z | connectivity_state | dns:firestore.googleapis.com:443 IDLE -> CONNECTING
2021-02-19T09:13:14.455Z | subchannel | 172.217.4.138:443 IDLE -> CONNECTING
2021-02-19T09:13:14.455Z | pick_first | CONNECTING -> CONNECTING
2021-02-19T09:13:14.456Z | resolving_load_balancer | dns:firestore.googleapis.com:443 CONNECTING -> CONNECTING
2021-02-19T09:13:14.456Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2021-02-19T09:13:14.456Z | connectivity_state | dns:firestore.googleapis.com:443 CONNECTING -> CONNECTING
2021-02-19T09:14:29.844Z | subchannel | 172.217.4.138:443 connection closed with error connect ETIMEDOUT 172.217.4.138:443
2021-02-19T09:14:29.847Z | subchannel | 172.217.4.138:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-19T09:14:29.847Z | pick_first | CONNECTING -> TRANSIENT_FAILURE
2021-02-19T09:14:29.848Z | resolving_load_balancer | dns:firestore.googleapis.com:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-19T09:14:29.848Z | channel | Pick result: TRANSIENT_FAILURE subchannel: undefined status: 14 No connection established
2021-02-19T09:14:29.848Z | call_stream | [0] cancelWithStatus code: 14 details: "No connection established"
2021-02-19T09:14:29.849Z | call_stream | [0] ended with status: code=14 details="No connection established"
2021-02-19T09:14:29.850Z | call_stream | [0] cancelWithStatus code: 1 details: "Cancelled on client"
2021-02-19T09:14:29.850Z | connectivity_state | dns:firestore.googleapis.com:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-19T09:14:32.654Z | channel | dns:firestore.googleapis.com:443 createCall [1] method="/google.firestore.v1.Firestore/BatchGetDocuments", deadline=Fri Feb 19 2021 17:19:32 GMT+0800 (China Standard Time)
2021-02-19T09:14:32.655Z | call_stream | [1] Sending metadata
2021-02-19T09:14:32.656Z | channel | Pick result: TRANSIENT_FAILURE subchannel: undefined status: 14 No connection established
2021-02-19T09:14:32.656Z | call_stream | [1] cancelWithStatus code: 14 details: "No connection established"
2021-02-19T09:14:32.656Z | call_stream | [1] ended with status: code=14 details="No connection established"
```

These debug messages, uh, seem to just say "No connection established" because of a timeout?

**Comment by ryanccn** [comment] 2021-02-19 09:18
For one thing, I'm on a personal MacBook Pro so my problem can't be because of corporate malware.

**Comment by zoheiry** [comment] 2021-02-22 10:30
I am also experiencing the same issue, any requests to firebase through proxy, hand indefinitely then timeout after 60000ms

**Comment by lnoir** [comment] 2021-02-22 11:16
Just in case it's useful to anyone that comes across this issue, I also had the problem with the connection timing out. After turning on additional logging, as recommended by @schmidt-sebastian, I saw firebase-admin was trying to connect to the host set in the `FIRESTORE_EMULATOR_HOST` environment variable. Removing it (or setting it to an empty string) fixed it.

**Comment by ryanccn** [comment] 2021-02-23 14:31
Looks like lots of people are having this problem but with different reasons 😅

**Comment by ryanccn** [comment] 2021-02-23 14:34
@lnoir Setting `FIRESTORE_EMULATOR_HOST` to an empty string resulted in an empty response from the API endpoint on my computer?

<img width="682" alt="Screen Shot 2021-02-23 at 22 32 50" src="https://user-images.githubusercontent.com/70191398/108858398-13079c00-7627-11eb-9dbf-f6dfb2f431b1.png">

**Comment by ryanccn** [comment] 2021-02-23 14:34
@inoir `172.217.4.138:443` is definitely not an emulator

**Comment by schmidt-sebastian** [comment] 2021-02-24 16:51
@zoheiry If you are experiencing connection problems with the Web SDK (in a browser), take a look here: https://github.com/firebase/firebase-js-sdk/issues/1674

I am pointing at this because the 60s timeout+Proxy problem used to be very common on our other platforms. It is not applicable to the firebase-admin-node SDK however.

**Comment by ryanccn** [comment] 2021-02-27 04:37
After switching to using Shadowsocks there's now a different error:

```json
{
  "code":"ERR_INVALID_PROTOCOL",
  "details":"Getting metadata from plugin failed with error: Protocol \"https:\" not supported. Expected \"http:\"",
  "metadata":{"internalRepr":{},"options":{}}
}
```

**Comment by Ymirke** [comment] 2021-03-01 12:56
I had the same issue. docRef.set() and .get() methods timing out and getting error 14 messages.

Firebase emulator was setup with: ```export FIRESTORE_EMULATOR_HOST="localhost:8000"``` in cli initially.

Using extra logs - thank you @schmidt-sebastian!
```
GRPC_VERBOSITY=DEBUG
GRPC_TRACE=all
```
I saw that admin sdk was trying to access port 8000 without emulators running.

Removing it with ```export FIRESTORE_EMULATOR_HOST=undefined``` in cli resolved it. Thanks @lnoir

----------------

Setting ```FIRESTORE_EMULATOR_HOST``` is currently the recommended (only?) way in the [firebase admin sdk docs](https://firebase.google.com/docs/emulator-suite/connect_firestore#admin_sdks) to enable the emulator. This can cause issues if you run tests with the emulator and set the ENVAR using CLI and don't remember to remove it. - It is fixed by setting ```FIRESTORE_EMULATOR_HOST``` programmatically in a ```beforeAll``` and removing it in an ```afterAll```

Maybe having .useEmulator() in the admin sdk would be a better dev experience:

```js
export const db =
  process.env.NODE_ENV === 'production' ? admin.firestore() : admin.firestore().useEmulator(port);
```

At the same time everything is working as it is intended as far as I can tell.

**Comment by hiranya911** [comment] 2021-05-27 22:46
Personally I'm not a fan of having to add an environment check to application code. I think what might be useful is if the Firestore client just logged a message out whenever it's connecting to the local emulator. That way there's a clear feedback of what's going on, in case somebody forgot to clear their env variables.

**Comment by elucidsoft** [comment] 2021-11-10 21:11
I have identified the issue causing this, and its been introduced in the past year or so, I do not know at what point.  But basically what's happening is it seems admin is spinning up a background task, and runs with that context.  When your app shutsdown, that background task can sometimes hang around, so on the next time initializeApp is called it appears to work fine but any method calls will just hang forever.  I have played around with app().delete() which does fix the problem but then you get even more strange behavior.  Because even though app().delete() was called by the previous instance on app shutdown, and an entirely new instance is spun up and a new initializeApp() is called, the new instance will sometimes throw an exception saying "The ["DEFAULT"] app has been deleted.".  I think the only way to handle this is to create instances of the app with a unique id each time, and then dispose of those that way you don't encounter this race condition on the DEFAULT app.

**Comment by inspire-lts** [comment] 2021-12-13 06:08
@ryanccn hello, do you fixed this problem? I also used proxy，I'm in china.

**Comment by ryanccn** [comment] 2021-12-14 10:58
> @ryanccn hello, do you fixed this problem? I also used proxy，I'm in china.

No... I've stopped using Firebase. But I would certainly like to see this problem solved 😇

**Comment by simbathesailor** [comment] 2022-01-25 12:29
Yes looks like it is some issue with corporate vpn or any other software companies have installed. Worked on personal laptop

**Comment by ryanccn** [comment] 2022-03-18 16:17
Using TUN can solve the problem.

**Closed** 2022-03-18 16:17 UTC
Labels: needs-triage, api: firestore
