### ISSUE TITLE
[Firestore] After a few hours Firestore QuerySnapshot listener stops receiving updates

### ISSUE THREAD

**Issue by chrisfraser** [firebase/firebase-admin-node#931] opened 2020-07-07 10:59 UTC
### Are you in the right place?

No, but I have been told by Firebase Support that [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) is not officially supported. There is an [issue](https://github.com/googleapis/nodejs-firestore/issues/1057) for this in nodejs-firestore, and a [workaround](https://github.com/googleapis/nodejs-firestore/pull/1220) has been merged, but it does not address the root cause and has not been pulled into this project. 

### Describe your environment

  * Operating System version: Ubuntu 18.04.4 LTS
  * Firebase Product: firebase-admin-node
  * Node.js version: v12.13.0
  * NPM version: 6.14.5
  * Packages: "firebase-admin": "8.13.0", "@google-cloud/firestore": "3.8.6"

### Describe the problem

After a period of time Firestore QuerySnapshot listener stops receiving updates. onError is not called.

### Steps to reproduce:

Please take a look at the following example: https://github.com/chrisfraser/firestore-onsnapshot-failure

It normally takes a couple hours for the issue to occur

#### Relevant Code:

``` js
const subscription = admin.firestore()
  .collection('yourCollection')
  .where('something', '==', 'query')
  .onSnapshot(
    (querySnapshot) => {
      console.log("This stops happening")
    },
    (error) => {
      console.error("If only we got one of these!")
    }
  );
```

#### EDIT
See [firestore.log](https://github.com/chrisfraser/firestore-onsnapshot-failure/blob/master/firestore.log) of an instance of this issue. 
Time of restart `"2020-07-06T08:17:44.171Z" [error]: 	Error: noUpdateThreshold exceeded, restarting server`

**Comment by mattstarkey** [comment] 2020-07-07 11:44
I'm experiencing the exact same issue, I have to restart my service every few hours to get around this.

**Comment by schmidt-sebastian** [comment] 2020-07-07 16:57
The workaround was released as part of 3.8.6, which matches the version range that `firebase-admin-node` uses. Please update your dependencies.

**Comment by chrisfraser** [comment] 2020-07-07 17:12
Please take a look at the [MCVE](https://github.com/chrisfraser/firestore-onsnapshot-failure). I am explicitly using `@google-cloud/firestore: "3.8.6"`. I have mentioned this in the description of my environment above. The test project has a three minute timeout and the workaround is not kicking in. 

I am more than a month into fighting this issue and I still have not had any feedback on the underlying cause of this issue. I appreciate the help @schmidt-sebastian, but a 2 minute watchdog in a realtime system is not a solution.

One of your products core promises, `Realtime updates`, is not working and nobody seems to be too concerned about fixing it. We are being charged for all the reads we have to do every time we restart our application to get back in sync and are losing customers as a result of this.

**Comment by bvrogers** [comment] 2020-07-09 15:05
I also have what appears to be exactly the same problem where I am performing multiple queries at the same time and some will just stop listening and receiving updates.

**Comment by turckj** [comment] 2020-07-09 16:03
I have been looking at my logs for a couple weeks now trying to explain this same disconnect, I believe I am experiencing this same issue. 
Can it be determined if this is an internal issue to the node.js library, or something happening on the firestore side?

**Comment by schmidt-sebastian** [comment] 2020-07-09 17:32
This is Google internal issue b/156308554.

**Comment by chrisfraser** [comment] 2020-07-12 19:01
Any update here please?

**Comment by lanbochen** [comment] 2020-07-14 14:38
Hi, I am the backend engineer for Firestore. We've identified a potential issue in another internal service which is a layer above our backend service handling the listeners and may cause the issue you have. We are working with the team who is responsible for this service for the root cause. In the meantime, we plan to change our backend to detect and kill stuck clients.

**Comment by chrisfraser** [comment] 2020-07-24 09:03
Thanks @lanbochen. Has this been done yet?

**Comment by lanbochen** [comment] 2020-07-29 03:35
We've made a change to kill stuck clients. It will be deployed next week.

**Comment by chrisfraser** [comment] 2020-07-29 10:47
Thanks for the update @lanbochen.

Does anyone know who we speak to to get a refund for the many millions of reads we have done to sync up our clients on restarts because of this issue?

**Comment by schmidt-sebastian** [comment] 2020-07-29 17:04
With the fix released with v3.8.6, you will _not_ be charged for extra reads if the SDK itself restarts the query.

For any additional billing that you may incurred, please reach out to cloud support. This is not something we can handle on GitHub.

**Comment by hiranya911** [comment] 2020-10-09 22:42
@schmidt-sebastian @lanbochen is this still being worked on?

**Comment by schmidt-sebastian** [comment] 2021-01-22 23:52
Closing this as we have no other updates at this point. Feel free to ping us to re-open.

**Closed by schmidt-sebastian** 2021-01-22 23:52 UTC
Labels: api: firestore
