### ISSUE TITLE
Getting auth/argument-error instead of auth/user-token-expired

### ISSUE THREAD

**Issue by resmall** [firebase/firebase-admin-node#185] opened 2018-01-17 16:36 UTC
### Describe your environment
  * Operating System version: Linux Mint 18
  * Firebase SDK version: 5.8.0
  * Library version: 5.8.0
  * Firebase Product: auth

#### Steps to reproduce:
When calling the `verifyIdToken(token)` function with an expired token, the exception code it throws is not the expected.
It throws a `auth/argument-error` but with the message stating that the token has expired. Instead it should throw a `auth/user-token-expired`, right?

#### Relevant Code (nodejs)
```
    admin.auth().verifyIdToken(token)
        .then(function(decodedToken) {
            // ok
        }).catch(function(error) {
            console.log(error); // Output below
        });
```

Console.log output of the error:
``` 
{ code: 'auth/argument-error',
     message: 'Firebase ID token has expired. Get a fresh token from your client app and try again. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.' }
```

**Comment by bojeil-google** [comment] 2018-01-17 17:57
Looks like a duplicate of https://github.com/firebase/firebase-admin-node/issues/179

**Comment by hiranya911** [comment] 2018-01-17 18:09
Correct. Lets close this and track via #179.

**Closed by hiranya911** 2018-01-17 18:09 UTC
Labels: duplicate
