### ISSUE TITLE
DEADLINE_EXCEEDED error with no debug info

### ISSUE THREAD

**Issue by BrodaNoel** [firebase/firebase-admin-node#465] opened 2019-02-24 23:59 UTC
# Note
I saw that there are 2 or 3 more issues opened (#349 and #452), related to this error, but none of them have the same stacktrace than my error. I created this another different issue because it may be related to another Quota exceded (more details below)

### Environment

  * Operating System version: On Google Cloud
```json
  "dependencies": {
    "@google-cloud/storage": "^2.4.1",
    "bcrypt": "^3.0.2",
    "busboy": "^0.3.0",
    "child-process-promise": "^2.2.1",
    "cors": "^2.8.4",
    "express": "^4.16.3",
    "fast-crc32c": "^1.0.4",
    "firebase-admin": "^7.0.0",
    "firebase-functions": "^2.2.0",
    "jsonwebtoken": "^8.4.0",
    "node-fetch": "^2.1.2",
    "nodemailer": "^4.6.8",
    "uuid": "^3.2.1"
  },
```
  * Firebase Product: Functions

### Step 3: Describe the problem
I'm getting some error logs on Firebase Functions, with no descriptions.
<img width="1168" alt="screen shot 2019-02-24 at 20 53 39" src="https://user-images.githubusercontent.com/1837969/53307349-4e273700-3876-11e9-977a-2195e85e3424.png">

**text**:
```
Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded
    at Object.exports.createStatusError (/user_code/node_modules/firebase-admin/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:618:8)
    at /user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:1029:24
```

Is there a way that you could catch these kind of errors and show something with more details? It's close to impossible to know why this is happening (thus, it's close to impossible to fix it).

Reading about this `DEADLINE_EXCEEDED`, I realized that it could happens for tons of different things. Mainly this is a "quota exceded". But, which of the one hundred quotas?

I could be something related to the Upload File Size in this case, but I'm not sure.
Do you know how could I catch these kind of error and understand a bit more about them?

### Edited: Adding information about how my code is implemented.
* This project was implemented with Firebase
* I run `firebase deploy` in my Terminal, in order to deploy it. The `firebase-tools` version that I'm using is `6.3.1`
* Some configurations, for example, timeouts and RAM, where changed using Google Cloud
* I'm using HTTP functions. There are 2 Functions implemented, with more than 50 endpoints listening different routes, using `express`. Here I share an example about how I'm implementing the function that is used to `upload` a file from the mobile App.

_remember this is not the full real code_
```js
'use strict';

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp({
  storageBucket: 'xxxxx'
});
const express = require('express');
const cors = require('cors')({origin: true});
const app = express();
const Busboy = require('busboy');
app.use(cors);

app.post('/user/login', (req, res) => {
  // ...
});

app.post('/photos/upload', (req, res) => {
  const bucket = admin.storage().bucket();
  const busboy = new Busboy({ headers: req.headers });
  
  busboy.on('file', () => {
    // Here some code about how to process the uploaded file
  });

  busboy.on('finish', () => {
    const options = {
      destination: `/photos/regular/${originalFileName}`,
      resumable: false,
      validation: 'crc32c'
    };

    bucket.upload(filename, options, (err, file, apiResponse) => {
      if (err) {
        res.status(400).send({ status: 'error', message: 'Upload failed', nativeError: err });
        return;
      }

      // Here more code about saving the photo in the DB
      db.save( photo)
        .then(() => {
          res.send({ status: 'ok' });
        });
      });
    });
  });
});


exports.app = functions.https.onRequest(app);

**Comment by wilhuff** [comment] 2019-02-25 19:47
@hiranya911 I don't think this is related to Firestore, since we have no notion of "Upload File Size". Possibly this is Storage? @BrodaNoel Could you confirm which product you're using that's giving you this error?

Speaking generally, DEADLINE_EXCEEDED is not related to quotas. DEADLINE_EXCEEDED is about the requests that you're making taking too long. Every request you make has a deadline associated with it, though this varies by product. For example, in Firestore, the default deadline is 60 seconds from request start.

**Comment by BrodaNoel** [comment] 2019-02-25 19:58
@wilhuff I changed the timeout to 120sec.
<img width="460" alt="screen shot 2019-02-25 at 16 51 21" src="https://user-images.githubusercontent.com/1837969/53364470-9e0d0900-391d-11e9-9b6a-2750a3b37133.png">

Another thing: I believe that every time that I sent a POST to the backend, with a file bigger than 10MB, I got that error. I read something about in some stackoverflow posts.
Here it says that the body size is 10MB: https://cloud.google.com/functions/docs/writing/http
```
Note: Cloud Functions limits HTTP request body sizes to 10MB, so any request larger than this will be rejected before your function is executed. We recommend uploading large files or files that persist beyond a single request directly to Cloud Storage
```

The problem is that that I actually have to upload it using a Firebase Function.
I'm doing it in this way (from a mobile App):

```js
    let formdata = new FormData();
    formdata.append('foo', 'bar');
    formdata.append(
      'photo',
      {
        uri: data.uri, // `data.uri` is the local file in the mobile device.
        name: 'image.jpg',
        type: 'multipart/form-data'
      }
    );

    fetch(
    'here the URL to the function',
    {
      method: 'POST',
      headers: {
        'Content-Type': 'multipart/form-data'
      },
      body
    }
  )
```

The curious thing, is that some weeks ago, when I was testing this Function, I got that error everytime I tried to upload a file bigger than 10MB. But the Function was enver called... So, seems like the error was throw before the function was executed. (anyway, I'm not 100% sure of this right now, because I did it a few weeks ago)

**Comment by wilhuff** [comment] 2019-02-25 20:48
I'm definitely not an expert on functions, but my understanding is that the timeout you've modified is the [_execution_ timeout for the function](https://cloud.google.com/functions/docs/concepts/exec#timeout), not necessarily the timeout you're seeing.

Are you certain this deadline exceeded isn't coming from anything you're using in your function?

How long is the POST taking?

**Comment by BrodaNoel** [comment] 2019-02-25 20:53
@wilhuff Wait... I believe we are missing the focus a bit.

There are 2 different situations here:

1. Some weeks ago, when I received this error, I was uploading files bigger than 10MB, and I do not rememeber how much time it was taking (but I guess it was less than 60seconds... anyway I'm not sure).

2. The second point, is the current issue reported. In this issue I reported that I'm seeing some errors in the logs. How much those calls are taking? I don't know. Why? Because the App is in production, so, those errors are coming from real devices. What are those user doing while that error is happening? I don't know. That's why I want to get a better error log (check the issue title) to understand what the user is doing while getting that error.

**Comment by hiranya911** [comment] 2019-02-25 21:00
@BrodaNoel what Admin SDK APIs are you using? Are you using Firestore or Cloud Storage? It would be best if you can share your code, so we don't have to guess. 

Issues #349 and #452 are both Firestore-specific, and I have a feeling your problem is different. But we are not able to glean anything useful from the information you've shared so far. If your request is more about getting better error logs from Functions, that is not that can be addressed in this repo. It should be reported to GCP/Functions support.

**Comment by BrodaNoel** [comment] 2019-02-25 23:04
@hiranya911 I just updated the original issue. At the end of the description, I added a code example about how I'm implementing it. Check the `Edited: Adding information about how my code is implemented.` title.

There is something important that you should know: I never uploaded a code example about how I'm implementing it, just because seems like NONE of the lines of code that I wrote, are executed. So, this seems to be a problem right before starting executing my express route. It seems to be something related to the handler that manages the request, before passing it to the express route (the `app.post`).

In the example, check that I added 2 routes, one for the login, and another for the upload.
I actually have close to 50 different express routes there, waiting for HTTP requests. **But I don't know in which of them I'm having the issue, due to the error log is not giving me any kind of information about the HTTP request**. So, the error may be happening in the login, or in the registration, or while uploading a file, etc.

Please, let me know if you need more information about anything.

**Comment by BrodaNoel** [comment] 2019-02-25 23:13
@hiranya911 anyway, you should understand that I'm not looking for help to fix my issue/error. I'm asking about adding more information in the error log. For example: The HTTP URL, the quota exceded (if this correspond), or something to understand where/when was the error is happening.

**Comment by BrodaNoel** [comment] 2019-02-25 23:18
Here I share the same error log, but how is it looking in Google Cloud:

<img width="1222" alt="screen shot 2019-02-25 at 20 16 44" src="https://user-images.githubusercontent.com/1837969/53375581-6b253e00-393a-11e9-9e8e-5ce6fd998dc7.png">

**Comment by wilhuff** [comment] 2019-02-25 23:30
This is a repository about firebase-admin-node library. While I'm sympathetic to your issue, nobody here is in a position to help with what you're asking for.

I was initially trying to understand if it was possible that the deadline exceeded could possibly have been caused by the libraries you were using as a part of the implementation of your functions. Those I could help with, but as @hiranya911 observed, this seems unlikely.

Your best bet is to do as suggested above: If your request is more about getting better error logs from Functions, that is not that can be addressed in this repo. It should be reported to GCP/Functions support.

**Comment by hiranya911** [comment] 2019-02-25 23:36
@BrodaNoel we cannot improve anything without knowing where (which API) the error is originating from. So that's why it was important to have a code sample. It looks like you're using Google Cloud Storage after all. That code is in https://github.com/googleapis/nodejs-storage, so if this turns out to be a GCS issue that's where the error message can be improved. 

But I really think this is an issue with the Functions runtime. So please report your issue at https://firebase.google.com/support/contact. Based on the provided information I don't see any action items for the Admin SDK or the Firestore SDK.

**Closed by hiranya911** 2019-02-25 23:36 UTC

**Comment by BrodaNoel** [comment] 2019-02-26 00:17
@hiranya911 @wilhuff Thank you a lot for your time guys.

Following the stack trace file (`/user_code/node_modules/firebase-admin/node_modules/grpc/src/common.js`), I'll report this on `https://www.npmjs.com/package/grpc`

**Comment by hiranya911** [comment] 2019-02-26 00:42
@BrodaNoel this is not a problem with one specific Node.js library (at least I don't think so). It is probably caused by some complex interactions between your code, its dependencies and the Cloud Functions runtime.  Therefore I doubt reporting this at the `grpc` package will do any good. All `grpc` is doing here is throwing an exception upon encountering some error condition. But `grpc` probably doesn't have any context information leading up to the error. 

The team maintaining the Function runtime is the most likely to have all the context necessary to triage and debug an issue like this. Moreover, note that GCS Node.js client doesn't even use `grpc`. It uses HTTP/REST to communicate with the backend service. So the fact that you have `grpc` error traces further indicate this is a runtime problem.

**Comment by BrodaNoel** [comment] 2019-02-26 22:22
Thank you a lot @hiranya911 
I just sent a report to https://firebase.google.com/support/contact, pointing to this issue
