### ISSUE TITLE
Updating getAll api in firestore

### ISSUE THREAD

**Issue by hadyrashwan** [firebase/firebase-admin-node#432] opened 2019-01-01 07:51 UTC
###  Describe your environment

  * Operating System version: Ubuntu 18.04
  * Firebase SDK version:  6.1.1
  * Library version: 6.4.0
  * Firebase Product: Firestore 

###  Describe the problem
After upgrading, I faced the change of `getAll` API I looked into the documentation but I still can't get my head around it.

https://cloud.google.com/nodejs/docs/reference/firestore/0.19.x/Firestore#getAll
https://cloud.google.com/nodejs/docs/reference/firestore/0.16.x/Firestore#getAll

#### Steps to reproduce: 
 create a new project with latest admin SDK and TypeScript option. Then try to utilize the new getAll API dynamically  

#### Relevant Code:

My code is as follows using the old SDK version
```
    const refs  = ids.map(id => firestoreRef.doc(`${path}/${id}`));
    const promise = await firestoreRef.getAll(...refs);
```

Updating it into the following still doesn't solve the problem
```
    const refs  = ids.map(id => firestoreRef.doc(`${path}/${id}`));
    const promise = await firestoreRef.getAll(...refs,null);
```

**Comment by hiranya911** [comment] 2019-01-02 05:02
Duplicate of https://github.com/googleapis/nodejs-firestore/issues/501

**Closed by hiranya911** 2019-01-02 05:02 UTC
