### ISSUE TITLE
angular-universal | firebase-admin | code: 'app/invalid-credential' |socket hang up on

### ISSUE THREAD

**Issue by Skillnter** [firebase/firebase-admin-node#72] opened 2017-08-16 07:20 UTC
[REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 5.1.0
  * Library version:  <What?>
  * Firebase Product: Cloud Messaging 

 [REQUIRED] Step 3: Describe the problem
```
import * as admin from 'firebase-admin';
var serviceAccount = require('./keys/keyfile.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://test.firebaseio.com"
});

var registrationToken = "--some-key--";

var payload = {
  notification: {
    title: "$GOOG up 1.43% on the day",
    body: "$GOOG gained 11.80 points to close at 835.67, up 1.43% on the day."
  },
  data: {
    stock: "GOOG",
    open: "829.62",
    close: "635.67"
  }
};


function panelMessage(){
admin.messaging().sendToDevice(registrationToken, payload)
  .then(function(response) {
    // See the MessagingDevicesResponse reference documentation for
    // the contents of response.
    console.log("Successfully sent message:", response);
  })
  .catch(function(error) {
    // console.log(serviceAccount);
    var date = new Date();
    console.log(date.toString());
    console.log("Error sending message:", error);
  });
}
```
I run this code through node and it work but when i add it in angular-universal

> server.ts

file.. it give the following error..
```
Error sending message: { Error: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "socket hang up". at FirebaseAppError.Error (native) at FirebaseAppError.FirebaseError [as constructor] (D:\angular2MH\firebase - panel\panel\node_modules\firebase-admin\lib\utils\error.js:39:28) at new FirebaseAppError (D:\angular2MH\firebase - panel\panel\node_modules\firebase-admin\lib\utils\error.js:84:23) at D:\angular2MH\firebase - panel\panel\node_modules\firebase-admin\lib\firebase-app.js:119:23 at ZoneDelegate.invoke (D:\angular2MH\firebase - panel\panel\node_modules\zone.js\dist\zone-node.js:232:26) at Zone.run (D:\angular2MH\firebase - panel\panel\node_modules\zone.js\dist\zone-node.js:114:43) at D:\angular2MH\firebase - panel\panel\node_modules\zone.js\dist\zone-node.js:502:57 at ZoneDelegate.invokeTask (D:\angular2MH\firebase - panel\panel\node_modules\zone.js\dist\zone-node.js:265:35) at Zone.runTask (D:\angular2MH\firebase - panel\panel\node_modules\zone.js\dist\zone-node.js:154:47) at drainMicroTaskQueue (D:\angular2MH\firebase - panel\panel\node_modules\zone.js\dist\zone-node.js:401:35)
errorInfo: { code: 'app/invalid-credential', message: 'Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "socket hang up".' } }
```
I checked the time (read at many place that could be the issue) and they are all synced.. Can anyone help me out with the issue? I'm using this repository https://github.com/Skillnter/angular-universal

 Steps to reproduce:
1). Get the angular-universal from git https://github.com/Skillnter/angular-universal
2). open file <working Directory of angular-universal repo>\src\server.ts
3).  write the following code with respective values of keyfile and 
```
import * as admin from 'firebase-admin';
var serviceAccount = require('./keys/keyfile.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://test.firebaseio.com"
});

var registrationToken = "--some-key--";

var payload = {
  notification: {
    title: "$GOOG up 1.43% on the day",
    body: "$GOOG gained 11.80 points to close at 835.67, up 1.43% on the day."
  },
  data: {
    stock: "GOOG",
    open: "829.62",
    close: "635.67"
  }
};


function panelMessage(){
admin.messaging().sendToDevice(registrationToken, payload)
  .then(function(response) {
    // See the MessagingDevicesResponse reference documentation for
    // the contents of response.
    console.log("Successfully sent message:", response);
  })
  .catch(function(error) {
    // console.log(serviceAccount);
    var date = new Date();
    console.log(date.toString());
    console.log("Error sending message:", error);
  });
}
```
and use the panelMessage function after server started..

```
let server = app.listen(app.get('port'), () => {
  
  console.log(`Listening on: http://localhost:${server.address().port}`, __dirname);

  panelMessage();
  
});
```
4). open CMD(windows)/terminal(Linux) and run "npm start" in the working directory of angular-universal

**Comment by hiranya911** [comment] 2017-08-24 22:01
Does it work locally, without angular?

**Comment by hiranya911** [comment] 2017-08-24 22:23
I just tried your repro steps, but I don't get any credential errors. Here's what I get:

```[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: dist/*server.js src/index.html
[nodemon] starting `node dist/server.js`
Listening at http://localhost:8000
Successfully sent message: { results: [ { error: [Object] } ],
  canonicalRegistrationTokenCount: 0,
  failureCount: 1,
  successCount: 0,
  multicastId: 7460003641957858000 }
```


I'm using a fake `registrationToken`, so the request eventually fails with the following error:

```
{"error":{"code":"messaging/invalid-registration-token","message":"Invalid registration token provided. Make sure it matches the registration token the client app receives from registering with FCM."}}
```

This means the request to the FCM server was actually authenticated and processed correctly. I'm on Ubuntu Linux, with latest Admin SDK (v5.2.1). Can you try this on a different environment and see if that leads anywhere? In any case this is most definitely an issue in your Angular environment, and not the Node SDK.

**Comment by Skillnter** [comment] 2017-08-25 12:09
@hiranya911  can you try with a real token? Is there any configuration needs to be done on firebase console?

**Comment by hiranya911** [comment] 2017-08-25 16:55
I'm not able to build this new repo:

```
ERROR in [default] ~/Projects/firebase-admin-node/universal-starter-latest/node_modules/@types/cookie-parser/index.d.ts:17:45 
    Cannot find name 'object'.
    
ERROR in [default] ~/Projects/firebase-admin-node/universal-starter-latest/node_modules/@types/cookie-parser/index.d.ts:19:81 
    A computed property name must be of type 'string', 'number', 'symbol', or 'any'.

ERROR in [default] ~/Projects/firebase-admin-node/universal-starter-latest/node_modules/@types/cookie-parser/index.d.ts:19:82 
    Cannot find name 'P'.
   ....
```

I recommend you use a library like https://www.npmjs.com/package/global-request-logger to log the HTTP/S calls made by the SDK, and see  what's going on. Based on the error message you've shared in the original post, your app doesn't even make a call to FCM servers. It fails before that, while trying to obtain an OAuth2 token from the credential. You can also try to execute a database write and see if the issue is localized to FCM API or not (unlikely).

Here's the source of the error: https://github.com/firebase/firebase-admin-node/blob/master/src/firebase-app.ts#L153

**Comment by Skillnter** [comment] 2017-08-25 17:59
@hiranya911  repo updated... cookie error fixed.. please check it now....

**Comment by hiranya911** [comment] 2017-08-26 01:45
New build errors...

```
ERROR in [default] ~/Projects/firebase-admin-node/universal-starter-latest/src/server.ts:98:23 
    Cannot find module 'firebase-admin'.
```

From server.ts:
```
     98 import * as admin from 'firebase-admin';
     99 var serviceAccount = require('./keys/key.json');
    100 admin.initializeApp({
    101   credential: admin.credential.cert(serviceAccount),
    102   databaseURL: "https://test.firebaseio.com"
    103 });
```

The library is installed:
```
$ ls node_modules/firebase-admin/
lib  LICENSE  node_modules  npm-shrinkwrap.json  package.json  README.md
```

**Comment by hiranya911** [comment] 2017-09-27 00:05
I'm closing this since I couldn't repro this with the publicly available version of angular.

**Closed by hiranya911** 2017-09-27 00:05 UTC
