### ISSUE TITLE
Calling getUser() right after importUsers() causes Internal error

### ISSUE THREAD

**Issue by kosuel** [firebase/firebase-admin-node#1362] opened 2021-07-08 03:44 UTC
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OS 11.4
  * Firebase SDK version: 9.14.0
  * Firebase Product: auth
  * Node.js version: 14
  * NPM version: 7.17.0

#### Steps to reproduce:

1. Import user for custom authentication.
2. Get user record which is just successfully imported.

Result: 
errorInfo: {
    code: 'auth/internal-error',
    message: 'INTERNAL ASSERT FAILED: Invalid user info response'
}

#### Relevant Code:

```
      const kakaoProviderId = "kakao.com";

      const userImportRecord : admin.auth.UserImportRecord = {
        uid: userId,
        email: email,
        emailVerified: emailVerified,
        providerData: [{uid: userId,
          providerId: kakaoProviderId}],
        disabled: false,
      };

      const importResults = await admin.auth().importUsers([userImportRecord]);
      if (importResults.failureCount === 0) {
         const user = await admin.auth().getUser(userId); => Error
      }
}
```

**Comment by bojeil-google** [comment] 2021-07-08 18:03
At first glance, `kakao.com` is not a supported provider ID. It seems like you uploaded a user in a bad format.

**Comment by hiranya911** [comment] 2021-07-09 22:42
@bojeil-google should we error out for invalid providers?

**Comment by bojeil-google** [comment] 2021-07-09 22:47
> @bojeil-google should we error out for invalid providers?

The problem is we'd have to hardcode these client side and the list of supported providers is likely to be updated with time.
It may be better if our backend do the validation and error when unsupported providers are used.

**Comment by kosuel** [comment] 2021-07-11 23:58
@bojeil-google I am working on custom authentication and play with admin.auth().createCustomToken api. 

There are two apis to create a user who's from outside of firebase. Let's say it's KakaoTalk user.
Those are admin.auth().createUser and admin.auth().importUsers. 
Here is my experiment.

First, importUsers() api:
1. when I use federated identity providers like facebook.com or gitHub.com, 
it works fine. But auth trigger, functions.auth.user().onCreate() is not called.

2. when I use custom provider like "kakao.com", calling admin.auth().getUser() gets error.
But I can see an imported user at Firebase Console. Interestingly user can sign in and gets provider information which is "kakao.com" from client api.

Second, createUser() api:
it works good and it also triggers functions.auth.user().onCreate() which is really cool! I don't need to copy same code after calling importUsers(). But problem is there is no way to attach provider information with this api. When I even fill up providerToLink property when I use this api, it does not work.

My question is what is best practice when I work with createCustomToken() api. importUsers or onCreate? How to set a provider information then?

**Comment by bojeil-google** [comment] 2021-07-12 04:02
`createCustomToken` will mint a custom token which when consumed by the [`signInWithCustomToken`](https://cloud.google.com/identity-platform/docs/reference/rest/v1/accounts/signInWithCustomToken) API will create a user. The user will be a custom token user and will not have a provider attached to it. Custom token users are typically not provisioned by the admin SDK.
You could call `createUser` and define the same `uid` as the one in the custom token. You can also set the relevant custom claims on that user but you can't link custom unsupported providers on that user.

I am not sure if `kakao.com` is OIDC compliant, but if so, you may define it as an OIDC provider (provider ID `oidc.kakao`). Generic OIDC providers are supported in [GCIP](https://cloud.google.com/identity-platform/docs/web/oidc).

**Comment by kosuel** [comment] 2021-07-13 04:41
@bojeil-google aha...OIDC. Good suggestion. I will try.

**Comment by bojeil-google** [comment] 2021-07-13 04:59
> @bojeil-google aha...OIDC. Good suggestion. I will try.

Let us know if it works. (keeping our fingers crossed)

**Comment by hiranya911** [comment] 2021-07-16 20:46
@bojeil-google is there any remaining action items for this? If we are not planning on any changes in the SDK, lets report an internal issue for the backend validation changes, and close this.

**Comment by bojeil-google** [comment] 2021-07-16 23:30
Done. I filed the internal bug.

**Closed by bojeil-google** 2021-07-16 23:30 UTC
Labels: api: auth
