### ISSUE TITLE
[Firestore]  I get this error when i install admin-sdk.

### ISSUE THREAD

**Issue by murataksu740** [firebase/firebase-admin-node#774] opened 2020-01-28 02:14 UTC
```



internal/crypto/sig.js:86
const ret = this[kHandle].sign(data, format, type, passphrase, rsaPadding,
^

Error: error:02016002:system library:stat:No such file or directory
at Sign.sign (internal/crypto/sig.js:86:29)
at Object.sign (/home/maksoboi/nodevenv/app/12/lib/node_modules/jsonwebtoken/node_modules/jwa/index.js:152:45)
at Object.jwsSign [as sign] (/home/maksoboi/nodevenv/app/12/lib/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:32:24)
at Object.module.exports [as sign] (/home/maksoboi/nodevenv/app/12/lib/node_modules/jsonwebtoken/sign.js:186:16)
at ServiceAccountCredential.createAuthJwt_ (/home/maksoboi/nodevenv/app/12/lib/node_modules/firebase-admin/lib/auth/credential.js:101:20)
at ServiceAccountCredential.getAccessToken (/home/maksoboi/nodevenv/app/12/lib/node_modules/firebase-admin/lib/auth/credential.js:75:26)
at FirebaseAppInternals.getToken (/home/maksoboi/nodevenv/app/12/lib/node_modules/firebase-admin/lib/firebase-app.js:64:73)
at AuthTokenProvider.getToken (/home/maksoboi/nodevenv/app/12/lib/node_modules/@firebase/database/dist/index.node.cjs.js:9231:27)
at PersistentConnection.establishConnection_ (/home/maksoboi/nodevenv/app/12/lib/node_modules/@firebase/database/dist/index.node.cjs.js:12133:18)
at Timeout._onTimeout (/home/maksoboi/nodevenv/app/12/lib/node_modules/@firebase/database/dist/index.node.cjs.js:12035:19) {
opensslErrorStack: [
'error:0E07606D:configuration file routines:module_run:module initialization error',
'error:0E07B075:configuration file routines:ssl_module_init:ssl command section empty'
],
library: 'system library',
function: 'stat',
reason: 'No such file or directory',
code: 'ERR_OSSL_SYS_NO_SUCH_FILE_OR_DIRECTORY'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/maksoboi/.npm/_logs/2020-01-28T02_10_27_751Z-debug.log
```
```

**Comment by schmidt-sebastian** [comment] 2020-01-28 17:21
@murataksu740 Sorry to hear about your troubles! This looks like you there is a problem opening a file description during SSL initialization. As this is somewhat deep in our stack, we will likely need a reproducible case to be able to debug this. Can you provide version information for your environment as well as a small reproduction?

I will also assign this to the Admin SDK team (I only work on Firestore).

**Comment by murataksu740** [comment] 2020-01-28 19:26
> @murataksu740 Sorry to hear about your troubles! This looks like you there is a problem opening a file description during SSL initialization. As this is somewhat deep in our stack, we will likely need a reproducible case to be able to debug this. Can you provide version information for your environment as well as a small reproduction?
> 
> I will also assign this to the Admin SDK team (I only work on Firestore).


Node.js version: 12.9.0
Firebase-Admin Version: 8.9.1
OS: Linux (Shared Hosting)

**Comment by hiranya911** [comment] 2020-01-28 20:56
Let's follow up at https://stackoverflow.com/questions/59941385/node-js-firebase-admin-fails-while-installing

Issue doesn't reproduce on Node 12 on Linux. This is a problem with your specific runtime environment -- most likely to do with how OpenSSL is set up there:

```
'error:0E07606D:configuration file routines:module_run:module initialization error',
'error:0E07B075:configuration file routines:ssl_module_init:ssl command section empty'
```

**Closed by hiranya911** 2020-01-28 20:56 UTC
Labels: api: firestore, needs-triage
