### ISSUE TITLE
[Firestore] [Emulator] RST_STREAM with code 2 triggered by internal client error: Protocol error

### ISSUE THREAD

**Issue by luigimassa** [firebase/firebase-admin-node#2376] opened 2023-11-18 20:32 UTC
* Operating System version: linux - ubuntu 23.10
  * Firebase SDK version: 10.5
  * Firebase Product: Firestore
  * Node.js version: v16.19.0
  * NPM version: 8.19.3

**Problem**

I tried a bulk upload in firestore emulator.
This is the error:
  details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
Do you have any suggestion? 
Thanks in advance
```
const admin = require('firebase-admin');
const firestore = admin.firestore();
const usersProfiles = require('./profileUsers.json');
firestore.settings({ preferRest: true });

const importaProfili = async () => {
  usersProfiles.forEach(async (profile) => {
    try {
      await firestore.collection('users').add(profile);
      console.log('success.');
    } catch (error) {
      console.log(`panic: `, error);
    }
  })
}
exports.importaProfili = importaProfili;
```

**Comment by lahirumaramba** [comment] 2023-12-06 16:55
Hey @ehsannas any thoughts on this? Thanks!

**Comment by ehsannas** [comment] 2023-12-06 21:33
hey @luigimassa, Thanks for reporting. I tried and wasn't able to reproduce the issue with 10,000 calls to `add` with the same settings (`preferRest: true`).

Are you setting the emulator host correctly? You should be doing something like this:

```js
firestore.settings({
  preferRest: true,
  host = "localhost:8080",
  settings.ssl = false
});
```

**Comment by ehsannas** [comment] 2023-12-15 15:11
Closing due to lack of further information.

**Closed by ehsannas** 2023-12-15 15:11 UTC
Labels: api: firestore

**Comment by luigimassa** [comment] 2023-12-21 09:58
Hello
I added your snippet, but there is same error
