### ISSUE TITLE
New Messaging api doesn't support condition topic negation

### ISSUE THREAD

**Issue by fantapop** [firebase/firebase-admin-node#235] opened 2018-03-20 02:28 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macos 10.13.3
  * Firebase SDK version: 
  * Library version: 5.11.0
  * Firebase Product: messaging

#### Steps to reproduce:

Try to send push notification to topic including negation, it results in the following error message:

Error sending message: { Error: Request contains an invalid argument.
    at FirebaseMessagingError.Error (native)
    at FirebaseMessagingError.FirebaseError [as constructor] (/Users/chris/Development/firebase-triggers/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/Users/chris/Development/firebase-triggers/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseMessagingError (/Users/chris/Development/firebase-triggers/node_modules/firebase-admin/lib/utils/error.js:241:16)
    at Function.FirebaseMessagingError.fromServerError (/Users/chris/Development/firebase-triggers/node_modules/firebase-admin/lib/utils/error.js:271:16)
    at /Users/chris/Development/firebase-triggers/node_modules/firebase-admin/lib/messaging/messaging-api-request.js:140:50
    at process._tickCallback (internal/process/next_tick.js:109:7)
  errorInfo:
   { code: 'messaging/invalid-argument',
     message: 'Request contains an invalid argument.' },
  codePrefix: 'messaging' }

I see that the node admin docs don't mention negation however all of ios, android and the http api do say its supported.  It appears that the node-admin api is using the http api.

#### Relevant Code:

```
const admin = require('firebase-admin');

const app = admin.initializeApp({
    credential: admin.credential.cert('/* add cert here */')
});

const message = {
    condition:  '!("my-test" in topics)',
    notification: {
        body: 'This is only a test',
        title: 'sweet title'
    }
};

admin.messaging().send(message)
  .then((response) => {
    console.log('Successfully sent message:', response);
  })
  .catch((error) => {
    console.log('Error sending message:', error);
  });
```

**Comment by hiranya911** [comment] 2018-03-20 03:21
Seems to be a problem with the backend API. I can reproduce it with the HTTP API directly. I've notified the FCM team.

**Comment by sampson-chen** [comment] 2018-05-31 20:03
Following up: FCM team has released a fix to the HTTP API and verified the fix in April, so closing this for now.

Please reopen if you are still able to reproduce the same issue =)

**Closed by sampson-chen** 2018-05-31 20:03 UTC
Labels: component: messaging
