### ISSUE TITLE
TypeError: Cannot read property 'charAt' of undefined 

### ISSUE THREAD

**Issue by xikimay** [firebase/firebase-admin-node#461] opened 2019-02-20 10:07 UTC
###  Environment

  * Operating System version: Mac Os Mojave 10.14
  * Firebase SDK version: latest
  * Library version: latest
  * Firebase Product: firestore, functions, auth (auth, database, storage, etc)

### The problem
In my Cloud Function, when I try to write on a document I have this error:

> TypeError: Cannot read property 'charAt' of undefined
>     at resolveURL (/user_code/node_modules/firebase-admin/node_modules/axios/lib/helpers/isURLSameOrigin.js:41:43)
>     at standardBrowserEnv (/user_code/node_modules/firebase-admin/node_modules/axios/lib/helpers/isURLSameOrigin.js:47:17)
>     at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/axios/lib/helpers/isURLSameOrigin.js:60:5)
>     at Module._compile (module.js:577:32)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/axios/lib/adapters/xhr.js:7:23)
>     at Module._compile (module.js:577:32)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at getDefaultAdapter (/user_code/node_modules/firebase-admin/node_modules/axios/lib/defaults.js:20:15)
>     at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/axios/lib/defaults.js:29:12)
>     at Module._compile (module.js:577:32)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/axios/lib/core/Axios.js:3:16)

Everything worked very well until I added packages to make it compile with Universal.
I think there is a conflict with a package but, I can't find the one. I suspect Domino and axios used by the firebase-admin at the moment but not sure ...
I'm confused with this problem, I can give you an additional explanation if needed 

## Code 
The 'set' and 'update' method are returning an error

```
const firebase = require('firebase-admin');

var db = firebase.firestore();

db.collection("users").doc("xikimay@gmail.com").set({
        anything: "test"
})
```

## function/package.json

```
{
  "name": "functions",
  "scripts": {
    "build": "cp -r ../dist . && tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@angular/animations": "7.1.4",
    "@angular/common": "7.1.4",
    "@angular/compiler": "7.1.4",
    "@angular/core": "7.1.4",
    "@angular/fire": "^5.1.1",
    "@angular/forms": "7.1.4",
    "@angular/http": "7.1.4",
    "@angular/platform-browser": "7.1.4",
    "@angular/platform-browser-dynamic": "7.1.4",
    "@angular/platform-server": "7.1.4",
    "@angular/router": "7.1.4",
    "@kubernetes/client-node": "^0.8.1",
    "@ng-bootstrap/ng-bootstrap": "^4.0.3",
    "@nguniversal/common": "^6.0.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "angular-notifier": "^4.1.1",
    "angular2-promise-buttons": "^3.0.1",
    "body-parser": "^1.18.3",
    "compression": "^1.7.3",
    "core-js": "^2.4.1",
    "cors": "^2.8.5",
    "domino": "^2.1.2",
    "express": "^4.15.2",
    "firebase": "^5.0.2",
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.1.0",
    "google-auth-library": "^3.1.0",
    "instagram-private-api": "^0.6.8",
    "kubernetes-client": "^6.8.3",
    "mkdir-recursive": "^0.4.0",
    "ng2-material-dropdown": "^0.10.1",
    "ng5-slider": "^1.1.13",
    "ngx-chips": "^1.6.7",
    "node-mailjet": "^3.3.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "6.0.0",
    "rxjs-compat": "^6.4.0",
    "stripe": "^6.25.1",
    "xmlhttprequest": "^1.8.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.11.4",
    "@angular/cli": "7.1.4",
    "@angular/compiler-cli": "7.1.4",
    "@angular/language-service": "7.1.4",
    "@types/node": "^8.0.30",
    "codelyzer": "^4.0.2",
    "http-server": "^0.10.0",
    "mkdir-recursive": "^0.4.0",
    "pre-commit": "^1.2.2",
    "ts-loader": "^4.0.0",
    "tslint": "^5.7.0",
    "typescript": "3.1.6"
  },
  "private": true
}


```

EDIT:

With firebase.database() it works

**Comment by rsgowman** [comment] 2019-02-20 23:23
I can't reproduce this issue. (I create an app with your list of dependencies which writes to Firestore as you demonstrated, but everything worked fine.) Are you able to create a minimal project that demonstrates this?

**Comment by xikimay** [comment] 2019-02-21 11:15
I was able to reproduce the error, not exactly the same (depending on the package version)
The steps:
 - Start an angular-universal app: I used this template [universal-starter](https://github.com/angular/universal-starter)
- Modify Prerender.ts and Server.ts to add domino

Server.ts
```
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import {enableProdMode} from '@angular/core';
import {ngExpressEngine} from '@nguniversal/express-engine';
import {provideModuleMap} from '@nguniversal/module-map-ngfactory-loader';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { renderModuleFactory } from '@angular/platform-server';
import { mkdirSync } from 'mkdir-recursive';

import * as express from 'express';
import * as bodyParser from 'body-parser';

import * as compression from 'compression';

import {join} from 'path';
  import {createWindow } from 'domino';

enableProdMode();

export const app = express();
(global as any).XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;


app.use(compression());

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

const DIST_FOLDER = join(process.cwd(), 'dist');
const template = readFileSync(join(DIST_FOLDER, '/browser/', 'index.html')).toString();
const win = createWindow(template);
global['window'] = win;
global['navigator'] = win.navigator;

const {AppServerModuleNgFactory, LAZY_MODULE_MAP} = require(DIST_FOLDER+ '/server/main');

app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));

app.set('view engine', 'html');
app.set('views', DIST_FOLDER+ '/browser');


app.get('/redirect/**', (req, res) => {
  const location = req.url.substring(10);
  res.redirect(301, location);
});

app.get('*.*', express.static(DIST_FOLDER+ '/browser', {
  maxAge: '1y'
}));

app.get('/*', (req, res) => {
  console.log("app. get /")
  res.render('index', {req, res}, (err, html) => {
    if (html) {
      res.send(html);
    } else {
      console.log(err)
      res.send(err);
    }
  });
});

if (process.env.PRERENDER) {

    const routes = require('./static.paths').default;
    Promise.all(
        routes.map(route =>
            renderModuleFactory(AppServerModuleNgFactory, {
                document: template,
                url: route,
                extraProviders: [
                    provideModuleMap(LAZY_MODULE_MAP)
                ]
            }).then(html => [route, html])
        )
    ).then(results => {
        results.forEach(([route, html]) => {
            const fullPath = join('./public', route);
            if (!existsSync(fullPath)) { mkdirSync(fullPath); }
            writeFileSync(join(fullPath, 'index.html'), html);
        });
        process.exit();
    });

}

```

Prerender.ts

```
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import {readFileSync, writeFileSync, existsSync, mkdirSync} from 'fs';
import {join} from 'path';
import {createWindow } from 'domino';

import {enableProdMode} from '@angular/core';
// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

// Import module map for lazy loading
import {provideModuleMap} from '@nguniversal/module-map-ngfactory-loader';
import {renderModuleFactory} from '@angular/platform-server';
import {ROUTES} from './static.paths';

const BROWSER_FOLDER = join(process.cwd(), 'browser');

const index = readFileSync(join('browser', 'index.html'), 'utf8');


const win = createWindow(index.toString());
global['window'] = win;
global['navigator'] = win.navigator;

const {AppServerModuleNgFactory, LAZY_MODULE_MAP} = require('./server/main');
let previousRender = Promise.resolve();

ROUTES.forEach(route => {
  const fullPath = join(BROWSER_FOLDER, route);

  if (!existsSync(fullPath)) {
    mkdirSync(fullPath);
  }

  previousRender = previousRender.then(_ => renderModuleFactory(AppServerModuleNgFactory, {
    document: index,
    url: route,
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  })).then(html => writeFileSync(join(fullPath, 'index.html'), html));
});

```
- Change Firebase.json to redirect traffic to cloud function

```
{
  "functions": {
    "predeploy": "npm --prefix \"$RESOURCE_DIR\" run build"
  },
  "hosting": {
    "public": "dist/browser",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      { "source": "**", "function": "universal" }
    ]
  }
}
```


- Add your cloud functions test

```
import * as functions from 'firebase-functions'
const firebase = require('firebase-admin');

firebase.initializeApp(functions.config().firebase)

var db = firebase.firestore();


const server = require('../dist/server')

export const universal = functions.https.onRequest((request, response) => {
    server.app(request, response);
  });


export const onInit = functions.auth.user().onCreate((user, context) => {
    console.log("START")
    return new Promise(function(resolve, reject) {
        db.collection("users").doc("test").set({
            mdr: "test"
        }).then(res => {
            console.log(res)
            console.log("ok")
        }).catch(err => { console.log(err, "failed") })
    })
})
```

- Main Package.json

```
{
  "name": "ng-universal-demo",
  "version": "0.0.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/angular/universal-starter.git"
  },
  "contributors": [
    "AngularClass <hello@angularclass.com>",
    "PatrickJS <patrick@angularclass.com>",
    "Jeff Whelpley <jeff@gethuman.com>",
    "Jeff Cross <crossj@google.com>",
    "Mark Pieszak <mpieszak84@gmail.com>",
    "Jason Jean <jasonjean1993@gmail.com>",
    "Fabian Wiles <fabian.wiles@gmail.com>"
  ],
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "copy:hosting": "cp -r ./dist/browser/* ./public",
    "build:functions": "npm run --prefix functions build",
    "build": "ng build && npm run copy:hosting && npm run build:functions && npm run build:prerender",
    "lint": "ng lint ng-universal-demo",
    "build:client-and-server-bundles": "ng build --prod && ng run ng-universal-demo:server:production",
    "build:prerender": "npm run build:client-and-server-bundles && npm run compile:server && npm run generate:prerender",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "compile:server": "tsc -p server.tsconfig.json",
    "generate:prerender": "cd dist && node prerender",
    "serve:prerender": "cd dist/browser && http-server",
    "serve:ssr": "node dist/server"
  },
  "pre-commit": [],
  "private": true,
  "dependencies": {
    "@angular/animations": "7.1.4",
    "@angular/common": "7.1.4",
    "@angular/compiler": "7.1.4",
    "@angular/core": "7.1.4",
    "@angular/forms": "7.1.4",
    "@angular/http": "7.1.4",
    "@angular/platform-browser": "7.1.4",
    "@angular/platform-browser-dynamic": "7.1.4",
    "@angular/platform-server": "7.1.4",
    "@angular/router": "7.1.4",
    "domino": "^2.0.0",
    "firebase": "^5.0.2",
    "body-parser": "^1.18.3",
    "mkdir-recursive": "^0.4.0",
    "@nguniversal/common": "^6.0.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "core-js": "^2.4.1",
    "compression": "^1.7.3",
    "xmlhttprequest": "^1.8.0",
    "express": "^4.15.2",
    "reflect-metadata": "^0.1.10",
    "rxjs": "6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.11.4",
    "@angular/cli": "7.1.4",
    "@angular/compiler-cli": "7.1.4",
    "@angular/language-service": "7.1.4",
    "@types/node": "^8.0.30",
    "codelyzer": "^4.0.2",
    "http-server": "^0.10.0",
    "pre-commit": "^1.2.2",
    "ts-loader": "^4.2.0",
    "tslint": "^5.7.0",
    "typescript": "3.1.6"
  }
}
```



- Function/package.json

```
{
  "name": "functions",
  "scripts": {
    "build": "cp -r ../dist . && tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@angular/animations": "7.1.4",
    "@angular/common": "7.1.4",
    "@angular/compiler": "7.1.4",
    "@angular/core": "7.1.4",
    "@angular/forms": "7.1.4",
    "@angular/http": "7.1.4",
    "@angular/platform-browser": "7.1.4",
    "@angular/platform-browser-dynamic": "7.1.4",
    "@angular/platform-server": "7.1.4",
    "@angular/router": "7.1.4",
    "rxjs": "6.3.3",
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^2.2.0",
    "domino": "^2.0.0",
    "compression": "^1.7.3",
    "mkdir-recursive": "^0.4.0",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.10",
    "express": "^4.15.2",
    "body-parser": "^1.18.3",
    "zone.js": "^0.8.26",
    "xmlhttprequest": "^1.8.0",
    "@nguniversal/common": "^6.0.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0"
  },
  "devDependencies": {
    "typescript": "^3.2.2",
    "mkdir-recursive": "^0.4.0"
  },
  "private": true
}
```
> 

And launch onInit Function then you should have an error.
In this case it was slighly different because of the version of some packages

<img width="1307" alt="screenshot 2019-02-21 at 12 11 41" src="https://user-images.githubusercontent.com/9168553/53165009-e5b82b80-35d1-11e9-8616-c6694f20dcab.png">

**Comment by rsgowman** [comment] 2019-02-22 23:16
I can now reproduce the 'not supported' error (though not the 'charAt' error).

Looking at the top line in the stacktrace (protobufjs/src/root.js) it looks like protobufjs doesn't think it's using node. Which is odd, since this certainly looks like a node environment to me. I'll need to investigate this a bit more to figure out what's going on.

But in the meantime, try adding this to your index.ts file:

```typescript
import * as protobufjs from 'protobufjs'
...
export const onInit = functions.auth.user().onCreate(user, context) => {
    console.log(protobufjs.util.isNode);
    ...
```

For me, that seems to change the load order such that everything works.

**Comment by mikelehen** [comment] 2019-02-27 19:02
@xikimay I'm not very familiar with Angular Universal but my understanding is it's supposed to run angular applications server-side instead of in a browser.  Note that our firebase-admin-node SDK is not meant to run in a browser, so it's not too surprising that it breaks under Angular Universal.  You might try using the "client SDK" for firebase instead (i.e. the "firebase" package on npm).  It supports both browser and node.js so may have a better chance of working.

Failing that, you con try to get by with @rsgowman's workaround, but ultimately I'm not sure if this is a configuration that we support right now.  If you're able to isolate the issue to something we're doing wrong in the nodejs-firestore SDK (source here: https://github.com/googleapis/nodejs-firestore) we can take a closer look and see if we can address it.

cc/ @davideast and @jamesdaniels in case they have insight based on their familiarity with Angular.

**Comment by mikelehen** [comment] 2019-03-05 23:10
I'm going to close this issue for now as I'm not sure if this is a supported scenario.  For now I'd try using the "firebase" npm package or the workaround @rsgowman provided.  Else if you can isolate this to something we're doing wrong in the nodejs-firestore SDK, I'm happy to take another look.

**Closed by mikelehen** 2019-03-05 23:10 UTC
Labels: api: firestore
