### ISSUE TITLE
development_mode_mismatch when we try to patch whitelisted phone number

### ISSUE THREAD

**Issue by pratiknikam** [firebase/firebase-admin-node#405] opened 2018-11-30 15:25 UTC
### Environment

  * Operating System version: Ubuntu 14
  * Firebase library: `firebase-admin-node`
  * Library version: `6.3.0`
  * Firebase Product: auth

#### Steps to reproduce:

When we patch whitelisted phone number by passing same phone number as one of argument, it corrupts the auth record and doesn't allow us to login later. Is this intended behavior? We shouldn't be sending `phoneNumber` as one of argument to `update` call for whitelisted numbers? It works fine for regular numbers. 

1. Whitelist a phone number from phone auth provider.
2. Login with whitelisted number and logout.
3. Patch whitelisted number using [`updateUser`](https://github.com/firebase/firebase-admin-node/blob/48ac9d5aaf0181fe56bf274a07de07b1af76b204/src/index.d.ts#L232) method by passing same number as one of `UpdateRequest` property (`phoneNumber`).
4. Try to sign in with whitelisted number again. Sign in fails with following error. `DEVELOPMENT_MODE_MISMATCH`.

![image](https://user-images.githubusercontent.com/2853953/49297446-c86b3980-f488-11e8-9c00-7d5fe76febaf.png)

**Comment by bojeil-google** [comment] 2018-11-30 18:43
It seems like you already created a user with that phone number in step 2 (login with whitelisted number will create a user). Are you calling `updateUser` on a different user record with the same phone number? If so that should not work. 2 users can't have the same phone number.

**Comment by pratiknikam** [comment] 2018-11-30 21:10
I'm calling `updateUser` on same user record with same `phoneNumber`.

- For regular phone number, this operation goes fine and we can sign in works perfectly.
- For whitelisted phone number, this operation does goes fine but we can't sign in any longer.

So ideally if this operation isn't allowed then it shouldn't work for regular phone numbers too.

**Comment by bojeil-google** [comment] 2018-11-30 21:37
I see. So you saying that `updateUser` works with the test phone number on same user but sign in will fail after that. Seems like a bug. I will notify the right channels about this.

**Comment by pratiknikam** [comment] 2018-12-01 03:05
That's correct.

**Comment by long1eu** [comment] 2018-12-20 15:36
any news?

**Comment by hiranya911** [comment] 2018-12-21 18:09
We probably won't have an update for a few weeks (at least until holidays are over). @pratiknikam are you also encountering this issue? Any additional debug info you can add to the issue?

**Comment by pratiknikam** [comment] 2018-12-24 04:08
I was encountering issue until we found out what's causing it. So we put workaround in place. Steps to reproduce an issue are mentioned above.

**Comment by long1eu** [comment] 2019-01-01 12:06
can you shared your insights @pratiknikam

**Comment by pratiknikam** [comment] 2019-01-01 15:01
@long1eu insight about?

**Comment by long1eu** [comment] 2019-01-01 15:02
You said you had a workaround.

**Comment by pratiknikam** [comment] 2019-01-01 15:13
Workaround is not to patch whitelisted phone with `phoneNumber` as one of argument.

**Comment by paveli** [comment] 2019-01-10 14:00
I've got the same error while tried to sign in with previously created (from Admin SDK) user. After i've read here that "login with whitelisted number will create a user" I've deleted user and the sign in started to work (and the user was automatically added with first sign in).

**Comment by pratiknikam** [comment] 2019-01-12 22:59
@paveli If you patch that number by passing same number as one of argument (`phoneNumber`) then sign in will fail after that. That's what my issue is about.

**Comment by jrnk** [comment] 2019-01-21 15:27
We're experiencing the same problem, and it's blocking us to use a 'test account' tied to a test phonenumber. Now we need to sign in with regular phone numbers to tie them to a user, that surely can't be the way :) ?

**Comment by bojeil-google** [comment] 2019-02-23 04:09
The fix should be in prod at this point. You should not be getting the `development_mode_mismatch` error anymore.

**Comment by hiranya911** [comment] 2019-02-25 19:33
Closing as per the last comment. Please report if the problem is observed again.

**Closed by hiranya911** 2019-02-25 19:33 UTC
Labels: component: auth

**Comment by pedrorau** [comment] 2020-01-21 21:54
We're experiencing the same problem, so we cant use test account. We have to use real phone number to debug. Any news?

**Comment by ShivamDev31** [comment] 2020-05-05 19:01
Facing the same issue: 
`com.google.firebase.FirebaseException: An internal error has occurred. [ DEVELOPMENT_MODE_MISMATCH:Non-development mode Verification Proof given in development mode request. ]` while using test account. No problem while using real number.

**Comment by peppix2010** [comment] 2020-05-24 22:07
Facing the same issue:
PlatformException (PlatformException(FirebaseException, An internal error has occurred. [ DEVELOPMENT_MODE_MISMATCH:Non-development mode Verification Proof given in development mode request.
