### ISSUE TITLE
TypeError: instance.INTERNAL.registerComponent is not a function

### ISSUE THREAD

**Issue by siefix** [firebase/firebase-admin-node#722] opened 2019-12-10 21:40 UTC
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: _____
  * Firebase SDK version: _____
  * Firebase Product: admin
  * Node.js version: _____
  * NPM version: 6.13.3

Have tried with `firebase-admin` 8.8.0, 8.7.0, and 8.6.1 (the last 3 versions)
Running `firebase-functions` 3.3.0

#### Steps to reproduce:

I'm getting this error when I try to deploy Cloud Functions. `firebase deploy --only functions:FUNCTIONNAME`

Any idea what the problem is? Anyone else have this issue?

```
Error: Error occurred while parsing your function triggers.

TypeError: instance.INTERNAL.registerComponent is not a function
    at registerDatabase (/PATH/cloud-functions/functions/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:15165:39)
    at Object.<anonymous> (/PATH/cloud-functions/functions/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:15196:5)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at FirebaseNamespace.get [as database] (/PATH/cloud-functions/functions/node_modules/firebase-admin/lib/firebase-namespace.js:282:38)
```

**Comment by hiranya911** [comment] 2019-12-10 22:40
Duplicate of #717, #714

**Closed by hiranya911** 2019-12-10 22:40 UTC
Labels: needs-triage

**Comment by eiipaw** [comment] 2019-12-12 10:39
I followed the linked threads but no concrete solutions were provided.

@firebase/app doesnt fix the problem

**Comment by D0561910** [comment] 2019-12-16 13:36
it's work fo me. Thank alot

**Comment by LeoLetourneur** [comment] 2019-12-19 10:17
More clearly
`npm install @firebase/app --save`
was the solution

**Comment by shaibt** [comment] 2019-12-20 10:38
If it helps anyone see my comment here: https://github.com/firebase/firebase-admin-node/issues/714#issuecomment-567877071

`@firebase/app` should not be explicitly required on server side when `firebase-admin` is included but you have to be careful  `@firebase/app` isn't somewhere in your node_modules folder hierarchy.

**Comment by darthwalsh** [comment] 2020-01-05 09:48
It's possible that `@firebase/app` is expected to be in your `node_modules`, like if you're using `@firebase/testing`:

```bash
PS C:\code\> npm ls @firebase/app
myCode@1.0.0 C:\code
`-- @firebase/testing@0.16.4
  `-- firebase@7.6.1
    `-- @firebase/app@0.5.0
```

In my case, the fix was updating `@firebase/testing` from version 0.13 to 0.16.

**Comment by jomendez** [comment] 2021-01-25 01:53
In my case, I already had @firebase/app as part of firebase. I also have node 12 installed with Win 10

```
npm ls @firebase/app
functions@ C:\Users\me\source\repos\admin\functions
`-- firebase@5.2.4
  `-- @firebase/app@0.6.13

```

I fixed the issue by updating the firebase dependencies to the latest.

`npm i --save firebase@latest firebase-admin@latest firebase-functions@latest`

From my package.json:

  ```
  "firebase": "^8.2.4",
    "firebase-admin": "^9.4.2",
    "firebase-functions": "^3.13.1",
```
Note: Always update firebase-tool to the latest:

`   npm i -g firebase-tools@lates`
