### ISSUE TITLE
Allow "data" from payload containing JSON objects and not only Strings for FCM messaging [FR]

### ISSUE THREAD

**Issue by redward** [firebase/firebase-admin-node#1094] opened 2020-11-17 20:30 UTC
**Is your feature request related to a problem? Please describe.**
I cannot send a JSON object in nodejs through FCM messagin (admin.messaging().send(message)). It's quite the big difference with a notification to send custom data. I get always a "data must only contain string values". see https://github.com/firebase/firebase-admin-node/blob/0d7238040a115099c969021fd9d876788b61d88b/src/messaging/messaging-internal.ts#L102

Example: 
'''
var message = {
        data: {
          action : "LOGIN", 
          jsonObject : {
            test : "test1"
          }
        },
        token: user.token
      };
admin.messaging().send(message)
'''

**Describe the solution you'd like**
When a message is sent and the type of message is a "data" field, the validation should be on any, and not on string only.

**Describe alternatives you've considered**
do not validate "date" field, it can contain anything

**Comment by hiranya911** [comment] 2020-11-17 20:37
Duplicate of #102 

> do not validate "date" field, it can contain anything

Currently it cannot. Only strings are supported in the backend API: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

**Closed by hiranya911** 2020-11-17 20:37 UTC
Labels: needs-triage, type: feature request

**Comment by sheikx1221** [comment] 2022-10-29 08:25
Facing this issue and very much sad that the solution does not exists
Anyways devised my own simple solution for now, it may not work for some extraordinary cases

```
    function stringifyValues(obj: any) {
        for (let key of Object.keys(obj)) {
            switch (typeof obj[key]) {
                case "boolean":
                case "number":
                case "symbol":
                case "bigint":
                case "undefined":
                    obj[key] = JSON.stringify(obj[key]);
                    break;
                case "object":
                    if (obj[key] == null) obj[key] = JSON.stringify(null);
                    else obj[key] = stringifyValues(obj[key]);
                    break;
                case "string":
                    break;
                default:
                    obj[key] = JSON.stringify(obj[key]);
            }
        }
    
        return obj;
    }
```

This will convert values only from every other data type to string even for nested objects. FCM payload accepts objects and not JSON stringified string. This solution is working perfectly fine for my usecase.

**Comment by zouhirdev** [comment] 2024-07-13 22:02
same problem here only solution i found is converting datatype on both the client and the server wich is not convinient please fic
