### ISSUE TITLE
SecretParam TS type is not exported

### ISSUE THREAD

**Issue by gregfenton** [firebase/firebase-admin-node#2439] opened 2024-02-01 03:12 UTC
### Describe your environment

  * Operating System version: ***Mac Sonoma 14.3***
  * Firebase SDK version: ***v12.0.0***
  * Firebase Product: ***Admin SDK for NodeJS***
  * Node.js version: ***v18.17.1***
  * NPM version: ***9.8.1***
  * VSCode version: ***1.85.2***
  * ESLint version: ***8.56.0***
  * @typescript-eslint/eslint-plugin version: ***6.20.0***

### Describe the problem

Using VSCode with ESLint & TypeScript enabled, I am trying to write a function that takes the results of `defineSecret()` and does some processing on it to reduce code duplication across my project.  The issue is that the datatype returned, `SecretParam`, is not exported.

When trying:
```ts
import {SecretParam} from 'firebase-functions/params';
```

VSCode reports:
```
Module '"firebase-functions/params"' declares 'SecretParam' locally, but it is not exported.ts(2459)
index.d.ts(5, 67): 'SecretParam' is declared here.
```

TSC errors out with:
```
error TS2459: Module '"firebase-functions/params"' declares 'SecretParam' locally, but it is not exported.
```

#### Relevant Code:

The code below is throwing ESLint errors and fails to compile with `tsc`:

```ts
import {SecretParam} from 'firebase-functions/params';

export const safeGetConfigJsonVal = (secretKey: SecretParam): Record<string, any> => {
  if (!secretKey.value()) {
    throw new Error('secretKey.value() is null/undefined');
  }

  let myConfig;
  try {
    myConfig = JSON.parse(secretKey.value());
    return myConfig;
  } catch (ex) {
    throw new Error(
      `secretKey is not a valid JSON string: ${secretKey.value()}`
    );
  }
};
```

#### Workaround:

Put `// @ts-ignore` on the line immediately before the `import` line

**Comment by lahirumaramba** [comment] 2024-05-21 18:58
Looks like the issue may have been addressed in the functions SDK https://github.com/firebase/firebase-functions/blob/9c818713db511895a33378859ab1b9f2eef99179/src/params/types.ts#L429

If you are still experiencing this issue please open a new ticket on the https://github.com/firebase/firebase-functions/tree/master repo.

**Closed by lahirumaramba** 2024-05-21 18:58 UTC
Labels: needs-triage

**Comment by aamikus** [comment] 2025-01-30 20:02
This issue is still reproduced. firebase-functions/params doesn't export the different Params, it only uses them internally, which is why with TS5 the defineString, defineInt etc. variables cannot be exported

<img width="891" alt="Image" src="https://github.com/user-attachments/assets/eb0959de-a6b8-47dc-8d0c-4238d8f26b15" />
