### ISSUE TITLE
Wrong type definition for UserRecord

### ISSUE THREAD

**Issue by andrioli** [firebase/firebase-admin-node#196] opened 2018-01-26 22:40 UTC
### Describe your environment

  * Operating System version: any
  * Library version: 5.8.1
  * Firebase Product: admin

### Describe the problem

The types definitions of `UserRecord` is inconsistent with the [documentation](https://firebase.google.com/docs/reference/admin/node/admin.auth.UserRecord). For instance, the `displayName` and `photoUrl` may be `null` but in the interface `UserRecord` in the [type definition file](https://github.com/firebase/firebase-admin-node/blob/master/src/index.d.ts) they are required

#### Steps to reproduce:

Just compare the documentation with the type definition

#### Relevant Code:

```
  interface UserRecord {
    uid: string;
    email: string;
    emailVerified: boolean;
    displayName: string; // SHOULD BE string?
    phoneNumber: string;
    photoURL: string; // SHOULD BE string?
    disabled: boolean;
    metadata: admin.auth.UserMetadata;
    providerData: admin.auth.UserInfo[];
    passwordHash?: string;
    passwordSalt?: string;
    customClaims?: Object;
    tokensValidAfterTime?: string;

    toJSON(): Object;
}
```

I didn't compared all the types, just these two that relevant to my code.

**Comment by hiranya911** [comment] 2018-01-26 23:05
Those properties are always present on the object assigned to `null`. That's different from being optional. Therefore I believe the current type defs are correct.

**Comment by andrioli** [comment] 2018-01-26 23:16
No, in this case the type must be union type: `string|null`

**Comment by andrioli** [comment] 2018-01-27 00:23
> Those properties are always present on the object assigned to null.

And this is not true, with the following code I can generate `undefined` values by simply creating an user direct from firebase console admin.

```
export const createUser = functions.auth.user().onCreate((event) => {
  // event is Event<admin.auth.UserRecord>
  console.log(event.data);
  console.log(`The displayName is ${event.data.displayName}`);
  console.log(`The photoURL is ${event.data.photoURL}`);
});
```

Generated logs:
<img width="619" alt="screen shot 2018-01-26 at 10 19 14 pm" src="https://user-images.githubusercontent.com/499182/35465969-10b9ba52-02e7-11e8-9bea-1c0861da0773.png">

So I think this issue can be reopened.

**Comment by hiranya911** [comment] 2018-01-27 00:49
Fair enough. Over to @bojeil-google for a resolution. What should be the right behavior here. Other Admin SDKs (Java, Python etc) return `null` values here. But those languages also don't have a notion of `undefined`.

**Comment by bojeil-google** [comment] 2018-01-27 01:26
We currently set these directly from the raw JSON response:
https://github.com/firebase/firebase-admin-node/blob/master/src/auth/user-record.ts#L164

Hence why they are undefined.

We could OR that to null to be consistent with the documentation and the client SDK: https://firebase.google.com/docs/reference/js/firebase.UserInfo#displayName

If we do this, the types would be string | null.

The issue is that Firebase Functions uses a different implementation for populating the UserRecord.  Even if we make the change, there would still be discrepancy. 

Strict nullability was added since Typescript 2. I think that may explain some of these issues. I don't think we were adhering to that from the start.

**Comment by hiranya911** [comment] 2018-07-09 21:15
@bojeil-google can we resolve this by just updating our documentation? Change the type to `@type {string=}` for these fields?

**Comment by vlapo** [comment] 2018-10-31 14:59
Something new with this issue?

**Comment by bojeil-google** [comment] 2018-10-31 17:09
Sorry I have been swamped lately. I will try to resolve this soon.

**Comment by hiranya911** [comment] 2018-12-21 18:31
This has been fixed in https://github.com/firebase/firebase-admin-node/pull/421

Typings now indicate the optional fields correctly. The documentation has also been updated to indicate `(string or undefined)` where it matters.

**Closed by hiranya911** 2018-12-21 18:31 UTC
Labels: bug, component: auth

**Comment by ciriousjoker** [comment] 2023-02-08 14:05
@hiranya911 Why is this closed?

The interface still specifies (for example) the email and phoneNumber as:

```ts
email?: string;
```

In reality we get back `null` in those fields.

So the interface should be:

```ts
email: string | null;
```

I'm specifically talking about the `onCreate` handler from `firebase-functions` here, which gets a `UserRecord` from the `firebase-admin` as its first input.
