### ISSUE TITLE
[Firestore] writeResults end up being null in node12

### ISSUE THREAD

**Issue by edgesoft** [firebase/firebase-admin-node#741] opened 2019-12-21 12:14 UTC
* Operating System version: debian
  * Firebase SDK version: 8.9.0 and ^8.8.0
  * Firebase Product: Firestore
  * Node.js version: node:12-slim

  Getting the following error but not all the time. 

```js
commit error: TypeError: Cannot read property 'writeResults' of null
    at /app/node_modules/@google-cloud/firestore/build/src/write-batch.js:453:43
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at WriteBatch.commit_ (/app/node_modules/@google-cloud/firestore/build/src/write-batch.js:450:14)
```

This only happens in node12. Works in node8 and node11

**Comment by hiranya911** [comment] 2019-12-23 19:15
Please provide more information. At least a code sample that we can run to reproduce the error.

**Comment by schmidt-sebastian** [comment] 2019-12-26 02:04
@edgesoft It would also be helpful if you provided client-side logs (via `setLogFunction`). Thanks!

**Comment by hiranya911** [comment] 2020-01-24 21:39
Closing this due to lack of information or activity. Please reopen with the requested details.

**Closed by hiranya911** 2020-01-24 21:39 UTC
Labels: api: firestore

**Comment by JasoonS** [comment] 2020-03-31 16:33
This issue hasn't been resolved. I am getting this error with code directly from [the docs](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document):
```
db.collection('cities').doc('new-city-id').set({ data: "some data" });
```

I created a collection called 'cities' already, and this code throws the same error as mentioned in the  original issue.
It does hover create the document and set the data of the document. So the operation does work.

This is happening in v8.10.0, the latest version of the library.

Please test this, very simple example code.

I didn't work out how to add the `setLoginFunction` that you mentioned @schmidt-sebastian
