### ISSUE TITLE
Dependency to Node 8

### ISSUE THREAD

**Issue by dbacinski** [firebase/firebase-admin-node#428] opened 2018-12-20 13:08 UTC
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 18.04
  * Firebase SDK version: cloud-functions@1.0.0
  * Library version: firebase-admin@6.4.0
  * Firebase Product: functions

#### Steps to reproduce:

Runing `npm install` on node:6 docker base image results in:
```
cloud-functions@1.0.0 /builds/***/cloud-functions/functions
`-- UNMET PEER DEPENDENCY firebase-admin@6.4.0
  `-- @types/node@8.10.39 
```

It runs correctly on node:8 base image.

It seems that by accident dependency to node 8 was introduced. But it should work well on Node 6 according to docs. https://cloud.google.com/functions/docs/concepts/nodejs-6-runtime

I am using TypeScript.

**Comment by hiranya911** [comment] 2018-12-20 18:39
We've had this dependency for many months, and this is the first time somebody has reported an issue about it. We have many developers who use this library on Node 6. We also regularly test on Node 6 without errors. See build logs at https://travis-ci.org/firebase/firebase-admin-node

Also trying this locally, I get a successful installation:

```
$ node --version
v6.12.3
$ npm install firebase-admin 

> grpc@1.17.0 install /usr/local/google/home/hkj/Projects/firebase-admin-node/temp/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
[grpc] Success: "/usr/local/google/home/hkj/Projects/firebase-admin-node/temp/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node" is installed via remote

> protobufjs@6.8.8 postinstall /usr/local/google/home/hkj/Projects/firebase-admin-node/temp/node_modules/protobufjs
> node scripts/postinstall

/usr/local/google/home/hkj/Projects/firebase-admin-node/temp
└─┬ firebase-admin@6.4.0 
  ├─┬ @firebase/app@0.3.5 
  │ ├── @firebase/app-types@0.3.2 
  │ ├── @firebase/util@0.2.3 
  │ ├── dom-storage@2.1.0 
  │ ├── tslib@1.9.0
...
```

Looks like something else is causing the installation to fail in your Node 6 environment. Can you post a full build log along with you `package.json`?

**Comment by hiranya911** [comment] 2018-12-20 18:45
This dependency has been in place for over a year (added in 5.4.x release): https://github.com/firebase/firebase-admin-node/pull/98/files

**Comment by hiranya911** [comment] 2018-12-29 05:39
@dbacinski I managed to successfully build a Node 6 Docker image using your dependency set. See the attached log. I got the same warnings as you did, but no errors.

[docker-build.log](https://github.com/firebase/firebase-admin-node/files/2716081/docker-build.log)

I can also say that nothing has changed at our end between your successful build and the failing build. The latest `firebase-admin` release is v6.4.0, released about a week before this issue was first reported. I don't know what could have caused the difference in behavior. May be an out-of-date shrinkwrap file or a package.lock file in your project? Or perhaps something to do with gitlab-ci (perhaps they started enforcing npm peer dependencies)?

Only concrete recommendation we can make is to not use `firebase-admin@6.4.0` alongside `firebase-functions@2.0.5`. That peer dependency is declared as `~6.0.0`, so installing 6.4.0 is not recommended. 

I think you should follow up this issue with the gitlab community, since that seems to be the only environment where this can be reproduced. I will close this for now. But if you can provide a standalone repro (a Dockerfile or something similar that I can locally test), I'd be happy to take another look.

**Closed by hiranya911** 2018-12-29 05:39 UTC
