### ISSUE TITLE
Firestore.Blob is not accepted on document set via the admin.firestore

### ISSUE THREAD

**Issue by jimmykane** [firebase/firebase-admin-node#536] opened 2019-05-22 14:14 UTC
### [READ] Step 1: Are you in the right place?
YES

### [REQUIRED] Step 2: Describe your environment

  * Firebase SDK version:  ^6.0.2
  * Firebase Component: Firestore
  * Component version: _____

#### Steps to reproduce:

Cannot save Blob to document

#### Relevant Code:

This is an issue with the Admin firestore. On the client side it works. 

While trying to save a blob on my NODEJS Admin app I get 

```
 Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "Blob" (found in field data). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
``` 

However I do create that blob via the firestore blob class 

I do create this like so: 

```
// The import
import {firestore} from "firebase";

// The function 
export const parseQueue = functions.region('europe-west2').pubsub.schedule('every 1 minutes').onRun(async (context) => {

....code...

// The problem
writePromises.push(
          admin.firestore()
            .collection('users')
            .doc(userID)
            .collection('events')
            .doc(<string>event.getID())
            .collection('activities')
            .doc(<string>activity.getID())
            .collection('streams')
            .doc(stream.type)
            .set({
              type: stream.type,
              data: firestore.Blob.fromBase64String(new Buffer((Pako.gzip(JSON.stringify(stream.data), {to: 'string'})), 'binary').toString('base64')),
            }))
```
It seems that the admin firestore does not accept the Blob that is returned from `firestore.Blob.fromBase64String` or I am completly confused.

**Comment by jimmykane** [comment] 2019-05-22 15:10
I have double checked and the `firestore.Blob.fromBase64String` indeed does return a Blob instance but the admin.firestore() does not know how to serialize it ?

**Comment by hiranya911** [comment] 2019-05-22 18:23
Duplicate of https://stackoverflow.com/questions/56259153/cannot-save-custom-blob-to-firestore-admin-sdk

**Closed by hiranya911** 2019-05-22 18:23 UTC
Labels: api: firestore, needs-triage

**Comment by jimmykane** [comment] 2019-05-24 07:27
@hiranya911 Is the a streamlined way to store blobs so client and backend code looks the same?

**Comment by hiranya911** [comment] 2019-05-24 17:25
I don't think so. But you can try asking at https://github.com/googleapis/nodejs-firestore
