### ISSUE TITLE
Unresolved function or method collection()

### ISSUE THREAD

**Issue by therepo90** [firebase/firebase-admin-node#395] opened 2018-11-23 18:12 UTC
All newest versions.

In my Webstorm using firebase-admin package that has firestore() inside I can't make my webstorm to resolve the typings for firestore. Unexcluding node modules @google/cloud directory doesnt work. Neiether installing the @google/cloud directory by npm

There are some strange conflicts with FirebaseFirestore and firestore and no "@typings" directory ("typing" instead)

**Comment by hiranya911** [comment] 2018-11-26 19:56
Cannot reproduce with the given details. Please provide a minimum and complete repro. Also please note that there's no `@google/cloud` npm module. It's `@google-cloud/firestore`.

**Comment by johannesnormannjensen** [comment] 2018-11-27 15:09
I can reproduce this as well

**Comment by therepo90** [comment] 2018-12-18 09:51
Okay, i made a little workaround but still not understand why its not working. 

    const admin = require('firebase-admin'); and in the same file do :

export const firestore = admin.firestore;

When I dont export the firestore from here it doesnt resolve correctly for some reason

**Comment by johannesnormannjensen** [comment] 2018-12-18 13:33
I made it work as well.

As it turns out WebStorm cannot figure out the imports for a functions project at the root of an angular project. So you just have to open the functions project at the root of its directory instead if you want the typings.

**Comment by hiranya911** [comment] 2018-12-21 18:12
@therepo90 @johannesnormannjensen is there anything that needs to be done in this repo to resolve this? We don't have much experience with WebStorm, so I'd defer to your expertise.

**Comment by johannesnormannjensen** [comment] 2019-01-02 08:01
@hiranya911 No I don't think it is an issue with this repo. At least I found that it weren't in my case.

**Comment by hiranya911** [comment] 2019-01-02 21:40
Closing as per the last comment. We can revisit if their's more/new information related to this.

**Closed by hiranya911** 2019-01-02 21:40 UTC
