### ISSUE TITLE
messaging/authentication-error

### ISSUE THREAD

**Issue by campanagerald** [firebase/firebase-admin-node#303] opened 2018-07-10 02:15 UTC
* Operating System version: macOS High Sierra
  * Firebase SDK version: latest
  * Library version: latest
  * Firebase Product:  push notifications

I followed the firebase docs on how to create an firebase admin for push notifications. this is how i set it up.

const admin = require('firebase-admin');
const serviceAccount = require('../helpers/privateKey.json');
const { fireBasePushNotification } = require('../config');

admin.initializeApp({
credential: admin.credential.cert(serviceAccount),
databaseURL: fireBasePushNotification.database
});

var registrationTokens = [
'imagine this is a token'
];

var topic = 'myTopic'

admin.messaging().subscribeToTopic(registrationTokens, topic)
.then(function(response) {
// See the MessagingTopicManagementResponse reference documentation
// for the contents of response.
console.log('Successfully subscribed to topic:', response);
})
.catch(function(error) {
console.log('Error subscribing to topic:', error);
});

but when i tried to subscribe a topic it respond an error "messaging/authentication-error"
The SDK could not authenticate to the FCM servers. Make sure you authenticate the Admin SDK with a credential which has the proper permissions to send FCM messages. See Add Firebase to your app for documentation on how to authenticate the Admin SDKs.

I generated serviceAccountKey several times it doesnt work.

**Comment by hiranya911** [comment] 2018-07-10 17:57
Chances are some of your tokens do not belong to the same Firebase project. The API is working fine as far as I can tell.

**Comment by joseph1125** [comment] 2018-07-18 06:41
I also has this problem, it seems like the admin.initializeApp can't load the info from credential and go to ask the info from defaultCredientals instead.

I also discovered this problem happens since 5.13.0, rolling back to 5.12.1 solves this issue

**Comment by hiranya911** [comment] 2018-08-03 18:58
@campanagerald  Can you check this against the instructions at https://github.com/firebase/firebase-admin-node/issues/302#issuecomment-409042017?

**Comment by campanagerald** [comment] 2018-08-03 21:56
hi. thanks a lot guys. ill check it later.

**Comment by AlecksJohannes** [comment] 2018-08-09 02:00
Hi @hiranya911. I have the same error as well, I have already tried out the way you mentioned above but still not working.

P/S: Also I have tried to create a new service account.

**Comment by hiranya911** [comment] 2019-02-02 01:34
This hasn't been updated in a while. I'm going to close this. Feel free to reopen/comment if the problem is encountered again.

**Closed by hiranya911** 2019-02-02 01:34 UTC
Labels: component: messaging

**Comment by robertsLando** [comment] 2020-08-19 10:04
I'm having this issue too. It only happens when using `subscribeToTopic` and `unsubscribeFromTopic` functions, `send` functions seems are working as I don't get any error.

@hiranya911 Any help?

**Comment by hiranya911** [comment] 2020-08-19 17:00
I don't have any additional info than what's shared in my earlier comments. If the problem persists I'd recommend reaching out to Firebase Support along with your project ID and token information.

**Comment by bethany-dawn** [comment] 2020-10-29 15:46
I'm seeing this as well, but with the application default credentials. All other functions are fine.

**Comment by Sivakumar415** [comment] 2021-03-13 14:36
I am still facing this issue any solution for this?

**Comment by shubhamgupta-work** [comment] 2022-06-04 14:37
Go to GCP Dashboard in your project
search "API and Service"
In the "Enable APIs and Services" section, click  "+Enable APIs and Services", and search "cloud messaging".
Now go to "Cloud Messaging" and "Firebase Cloud Messaging API" one by one and enable it.

**Comment by ccarlsson-logi** [comment] 2024-01-02 08:55
Experiencing this issue as well, even after enabling Firebase Cloud Messaging API. Any fix for it?

**Comment by Rashibhattad15** [comment] 2025-05-10 11:00
@ccarlsson-logi  any update how you fixed it?
