### ISSUE TITLE
Firestore update is broken starting 5.5.1

### ISSUE THREAD

**Issue by lm1** [firebase/firebase-admin-node#191] opened 2018-01-19 22:20 UTC
Starting with firebase-admin 5.5.1 when performing an update within firestore transaction which contains both new nested fields and deletes some nested fields in the document, the new fields are silently dropped.

  * Operating System version: Win10
  * Firebase SDK version: 3.16.0
  * Library version: 5.5.1
  * Firebase Product: firestore

For example having a document which contains objects entries.G5VnUD and users.G5VnUD, but does not contain entries.LommiL nor users.LommiL the following operation results in deletion of entries.G5VnUD and users.G5VnUD, but the new nested fields are dropped on the floor without any warning.
```
transaction.update(docRef,
 { 'entries.LommiL':
   { time: 1516399412431,
     trainer: null,
     waiting: false,
     created: 1516399412431 },
  'users.LommiL': 1517342400000,
  'users.G5VnUD': {},
  'entries.G5VnUD': {}
});
```
Issue is still present in latest 5.8.1 but does not exist in 5.5.0

**Comment by hiranya911** [comment] 2018-01-20 06:14
@schmidt-sebastian can you take a look?

**Comment by schmidt-sebastian** [comment] 2018-01-24 18:47
Hi! Thanks for sending this over. Firebase Admin 5.5.1 pulled in Firestore 0.10.x, which contains some changes to how we process nested maps, so this issue sounds pretty scary. It does, however, not reproduce for me:

```
ref.set({users: {G5VnUD: {foo: 'bar'}}, entries: {G5VnUD: {foo: 'bar'}}})
      .then(() => ref.get())
      .then(doc => {
        console.log(doc.data());
      })
      .then(() =>
        firestore.runTransaction(transaction => {
          transaction.update(ref, {
            'entries.LommiL': {
              time: 1516399412431,
              trainer: null,
              waiting: false,
              created: 1516399412431,
            },
            'users.LommiL': 1517342400000,
            'users.G5VnUD': {},
            'entries.G5VnUD': {},
          });

          return Promise.resolve();
        })
      )
      .then(() => ref.get())
      .then(doc => {
        console.log(doc.data());
      });
```

This prints the following for me on 0.10.2: 

```
{ users: { G5VnUD: { foo: 'bar' } },
  entries: { G5VnUD: { foo: 'bar' } } }
```

and 

```
{ users: { LommiL: 1517342400000, G5VnUD: {} },
  entries: 
   { LommiL: 
      { trainer: null,
        time: 1516399412431,
        created: 1516399412431,
        waiting: false },
     G5VnUD: {} } }
```

Can you enable logging and send us your logs? You can pass `console.log` to here: https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L40

**Comment by schmidt-sebastian** [comment] 2018-01-26 23:31
Closing this issue for now as we can't reproduce this. Please ping us should this happen again.

**Comment by lm1** [comment] 2018-01-27 14:55
The same testcase fails for me when using deletion sentinels in place of empty object literals, i.e.:
```
  ref.set({users: {G5VnUD: {foo: 'bar'}}, entries: {G5VnUD: {foo: 'bar'}}})
  .then(() => ref.get())
  .then(doc => {
    console.log(doc.data());
  })
  .then(() =>
    firestore.runTransaction(transaction => {
      transaction.update(ref, {
        'entries.LommiL': {
          time: 1516399412431,
          trainer: null,
          waiting: false,
          created: 1516399412431
        },
        'users.LommiL': 1517342400000,
        'users.G5VnUD': admin.firestore.FieldValue.delete(),
        'entries.G5VnUD': admin.firestore.FieldValue.delete()
      });
      return Promise.resolve();
    })
  )
  .then(() => ref.get())
  .then(doc => {
    console.log(doc.data());
  });
```
this produces:
```
{ users: { G5VnUD: { foo: 'bar' } },
  entries: { G5VnUD: { foo: 'bar' } } }
```
and

`{ users: {}, entries: {} }`

Please re-open.

**Comment by Ziph0n** [comment] 2018-01-29 15:45
I'm also facing this issue

My database structure:

```
users
|___ id1
       |___ data
                   |___ left
                             |___ thing1 = 2
                             |___ thing1 = 20
                   |___ pro
                             |___ subscribed = true
       |___ ...
```

If I'm running this:

```
admin.firestore().collection("users").doc("id1").update({
    data: {
        pro: {
            subscribed: false
        }
    }
});
```

The "new" database structure is:

```
users
|___ id1
       |___ data
                   |___ pro
                             |___ subscribed = false
       |___ ...
```

I'm using firebase-admin 5.8.1

**Comment by lm1** [comment] 2018-01-29 15:50
@Ziph0n I think this behavior is actually expected, use `{ ['data.pro.subscribed']: false }` for nested field update.
I'm only seeing the issue with deletion sentinel in play.

**Comment by Ziph0n** [comment] 2018-01-29 16:10
@lm1 Indeed, thank you.

The Firebase team might want to update their documentation. They indeed mention the "dot notation"  but isn't present in the example below: https://firebase.google.com/docs/firestore/manage-data/add-data#update_fields_in_nested_objects

**Comment by schmidt-sebastian** [comment] 2018-01-29 22:45
> The Firebase team might want to update their documentation. They indeed mention the "dot notation" but isn't present in the example below: https://firebase.google.com/docs/firestore/manage-data/add-data#update_fields_in_nested_objects

It's part of the update call to update the value of the field `favorites.color`.

**Closed** 2018-01-30 00:03 UTC
Labels: component. firestore
