### ISSUE TITLE
Cloud Storage not using HTTP Agent set in AppOptions

### ISSUE THREAD

**Issue by seanemmer** [firebase/firebase-admin-node#962] opened 2020-07-22 01:07 UTC
#### Describe your environment

  * Operating System version: Mac OSX
  * Firebase SDK version: 8.0.0
  * Firebase Product: storage
  * Node.js version: 12.0.0
  * NPM version: yarn 1.0.0

#### Describe the problem

Firebase Storage does not use the httpAgent set in AppOptions

#### Steps to reproduce:

1) Initialize firebase using initializeApp with a custom httpAgent in the AppOptions object
2) Run any firebaseApp().storage() function that results in an HTTP request (e.g. getSignedUrl())
3) The HTTP request is not handled by the httpAgent

**Comment by hiranya911** [comment] 2020-07-22 17:30
There's no way to pass an `http.Agent` into the `@google-cloud/storage` APIs. So this is working as intended. Unfortunately it's not mentioned in the documentation today. Only the limitations with RTDB and Firestore are indicated in the current docs:

```
Realtime Database and Firestore use other means of communicating with
the backend servers, so they do not use this HTTP Agent.
``` 

We can get this information updated. If your intention is to use the Storage APIs behind a proxy you can do so by setting the `https_proxy` environment variable. 

```
export https_proxy=http://localhost:3128
```

**Comment by seanemmer** [comment] 2020-07-22 17:56
Thanks @hiranya911 .

I need to provide an SSL certificate to my proxy, which is why I was trying to set the http.Agent.  Is there a way to do this with ENV variables?

**Comment by hiranya911** [comment] 2020-07-22 21:28
@seanemmer not quite sure how to achieve that. If it was just username+password auth, I suppose you could include that in the proxy URL. [Cloud Storage](https://www.npmjs.com/package/@google-cloud/storage) uses [Gaxios](https://www.npmjs.com/package/gaxios) to make HTTP calls, which in turns uses [HttpsProxyAgent](https://www.npmjs.com/package/https-proxy-agent) to provide proxy support. Perhaps look into the docs of these libraries or try filing a bug in their repos.

**Comment by seanemmer** [comment] 2020-07-22 23:25
Gaxios has the option to set your own agent.  In fact, so does https://github.com/googleapis/google-api-nodejs-client.

Unfortunately, firebase-admin does not expose this ability from Gaxios.  Is this something I should try to have addressed on the firebase-admin repo, or on @google-cloud/storage?

**Comment by hiranya911** [comment] 2020-07-23 02:20
It should be fixed in @google-cloud/storage. If they expose this ability then we can plumb the `http.Agent` specified in `admin.initializeApp()` through to their API.

**Comment by hiranya911** [comment] 2020-12-17 20:52
I'm going to close this as we don't have an immediate recourse in this repo. We can revisit this if the GCS server SDK provides a way to set http agent in the future.

**Closed by hiranya911** 2020-12-17 20:52 UTC
Labels: api: storage
